### PR TITLE
Add blosc precompiled binary for Windows

### PR DESCRIPTION
**Pull request by Corfucinas**
Windows installation is complaining about PEP 517, adding the binaries to solve that and smooth the installation process.

Binary downloaded from [here](https://www.lfd.uci.edu/~gohlke/pythonlibs/#blosc)

<details>
<summary> Error message </summary>
<br>
ERROR: Command errored out with exit status 1:
   command: 'D:\Github\freqtrade\.env\Scripts\python.exe' 'D:\Github\freqtrade\.env\lib\site-packages\pip\_vendor\pep517\_in_process.py' build_wheel 'C:\Users\pedro\AppData\Local\Temp\tmprkojz9na'
       cwd: C:\Users\pedro\AppData\Local\Temp\pip-install-qtf4v4z1\blosc
  Complete output (162 lines):
  Not searching for unused variables given on the command line.
  -- The C compiler identification is unknown
  CMake Error at CMakeLists.txt:3 (ENABLE_LANGUAGE):
    No CMAKE_C_COMPILER could be found.

    Tell CMake where to find the compiler by setting either the environment
    variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
    the compiler, or to the compiler name if it is in the PATH.

  -- Configuring incomplete, errors occurred!
  See also "C:/Users/pedro/AppData/Local/Temp/pip-install-qtf4v4z1/blosc/_cmake_test_compile/build/CMakeFiles/CMakeOutput.log".
  See also "C:/Users/pedro/AppData/Local/Temp/pip-install-qtf4v4z1/blosc/_cmake_test_compile/build/CMakeFiles/CMakeError.log".
  Not searching for unused variables given on the command line.
  CMake Error at CMakeLists.txt:2 (PROJECT):
    Generator

      Visual Studio 15 2017 Win64

    could not find any instance of Visual Studio.

  -- Configuring incomplete, errors occurred!
  See also "C:/Users/pedro/AppData/Local/Temp/pip-install-qtf4v4z1/blosc/_cmake_test_compile/build/CMakeFiles/CMakeOutput.log".
  Not searching for unused variables given on the command line.
  -- The C compiler identification is unknown
  CMake Error at CMakeLists.txt:3 (ENABLE_LANGUAGE):
    The CMAKE_C_COMPILER:

      cl

    is not a full path and was not found in the PATH.

    To use the NMake generator with Visual C++, cmake must be run from a shell
    that can use the compiler cl from the command line.  This environment is
    unable to invoke the cl compiler.  To fix this problem, run cmake from the
    Visual Studio Command Prompt (vcvarsall.bat).

    Tell CMake where to find the compiler by setting either the environment
    variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
    the compiler, or to the compiler name if it is in the PATH.

  -- Configuring incomplete, errors occurred!
  See also "C:/Users/pedro/AppData/Local/Temp/pip-install-qtf4v4z1/blosc/_cmake_test_compile/build/CMakeFiles/CMakeOutput.log".
  See also "C:/Users/pedro/AppData/Local/Temp/pip-install-qtf4v4z1/blosc/_cmake_test_compile/build/CMakeFiles/CMakeError.log".
  Not searching for unused variables given on the command line.
  -- The C compiler identification is unknown
  CMake Error at CMakeLists.txt:3 (ENABLE_LANGUAGE):
    The CMAKE_C_COMPILER:

      cl

    is not a full path and was not found in the PATH.

    To use the JOM generator with Visual C++, cmake must be run from a shell
    that can use the compiler cl from the command line.  This environment is
    unable to invoke the cl compiler.  To fix this problem, run cmake from the
    Visual Studio Command Prompt (vcvarsall.bat).

    Tell CMake where to find the compiler by setting either the environment
    variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
    the compiler, or to the compiler name if it is in the PATH.

  -- Configuring incomplete, errors occurred!
  See also "C:/Users/pedro/AppData/Local/Temp/pip-install-qtf4v4z1/blosc/_cmake_test_compile/build/CMakeFiles/CMakeOutput.log".
  See also "C:/Users/pedro/AppData/Local/Temp/pip-install-qtf4v4z1/blosc/_cmake_test_compile/build/CMakeFiles/CMakeError.log".

  --------------------------------------------------------------------------------
  -- Trying "Ninja (Visual Studio 15 2017 Win64 v141)" generator
  --------------------------------
  ---------------------------
  ----------------------
  -----------------
  ------------
  -------
  --
  --
  -------
  ------------
  -----------------
  ----------------------
  ---------------------------
  --------------------------------
  -- Trying "Ninja (Visual Studio 15 2017 Win64 v141)" generator - failure
  --------------------------------------------------------------------------------

  --------------------------------------------------------------------------------
  -- Trying "Visual Studio 15 2017 Win64 v141" generator
  --------------------------------
  ---------------------------
  ----------------------
  -----------------
  ------------
  -------
  --
  --
  -------
  ------------
  -----------------
  ----------------------
  ---------------------------
  --------------------------------
  -- Trying "Visual Studio 15 2017 Win64 v141" generator - failure
  --------------------------------------------------------------------------------

  --------------------------------------------------------------------------------
  -- Trying "NMake Makefiles (Visual Studio 15 2017 Win64 v141)" generator
  --------------------------------
  ---------------------------
  ----------------------
  -----------------
  ------------
  -------
  --
  --
  -------
  ------------
  -----------------
  ----------------------
  ---------------------------
  --------------------------------
  -- Trying "NMake Makefiles (Visual Studio 15 2017 Win64 v141)" generator - failure
  --------------------------------------------------------------------------------

  --------------------------------------------------------------------------------
  -- Trying "NMake Makefiles JOM (Visual Studio 15 2017 Win64 v141)" generator
  --------------------------------
  ---------------------------
  ----------------------
  -----------------
  ------------
  -------
  --
  --
  -------
  ------------
  -----------------
  ----------------------
  ---------------------------
  --------------------------------
  -- Trying "NMake Makefiles JOM (Visual Studio 15 2017 Win64 v141)" generator - failure
  --------------------------------------------------------------------------------

  ********************************************************************************
  scikit-build could not get a working generator for your system. Aborting build.

  Building windows wheels for Python 3.8 requires Microsoft Visual Studio 2017.
  Get it with "Visual Studio 2017":

    https://visualstudio.microsoft.com/vs/

  ********************************************************************************
  ----------------------------------------
  ERROR: Failed building wheel for blosc
Failed to build blosc
ERROR: Could not build wheels for blosc which use PEP 517 and cannot be installed directly
</details>

### CODE REVIEW

**Comment by xmatthias** [comment]
I'm not quite certain about this ... 

looking at the original library, there seems to be efforts in getting the wheels to build (here https://github.com/Blosc/python-blosc/issues/131) - and they have comments that certain tests with the wheel from the source above do fail: https://github.com/Blosc/python-blosc/issues/131#issuecomment-353257366

Either way - without adding this step to the documentation, it'll be binary blobs that noone will ever remember.

Also - i think you'll need a c compiler for the python installation under windows anyway - as i strongly doubt that all other dependencies do build wheels (or don't use C dependencies)... but it's been a while since i tried that part.

**Comment by Corfucinas** [comment]
@xmatthias 

Yeah, the problem is that getting those libraries with Visual Studio usually translate to ~7 Gbs of disk space that unless you're working with low level stuff, C, C++ etc are just a waste of disk space, also, some packages complain about if you have the 2015 version, the 2017, the 2019....if you have all of those versions I'm sure it's over 11 Gbs easily.

If it's about the documentation, I can take care of that if you agree to include the binaries, they serve the same purpose as the Ta-Lib ones (which won't compile in Windows anyways unless you have the Visual Studio C compiler, so it's one of those things that, if you can compile `Ta-Lib`, you can't compile `blosc`, so you will need the binary anyways).

In any case, I was able to install Freqtrade after using the binaries I've included (also downloaded and backtest the new candlestick data, no problems at all).

**Comment by xmatthias** [comment]
yeah, i understand the purpose of the libraries - and thanks for the confimation that "the rest" of the installation seems to work without c compiler.
 
yes, please add it to the (windows) documentation (most likely right next to the ta-lib section) ... :+1:

**Comment by Corfucinas** [comment]
Sure thing @xmatthias !

I'll commit to this PR when ready (probably a few days since I'm busy at the office, but I'll take care of it). I never had any problems using pre-compiled binary for Python, ...so if I get a PEP 517 installation error I usually just go that way. 

I just checked the size of the libraries..

MSVC v142 - VS 2019 C++ => 4.99 GB.
MSVC v 141 VS 2017 C++ => 4.3 GB.
MSVC v140 - VS 2015 C++ build tools (v14.00) => 3.64 GB.

total 12.93 Gb.

**Comment by xmatthias** [comment]
Yeah - the preferred way to run freqtrade in windows is either via docker, or via WSL (if available) ...

The main reason for this is the installation size / problems you point out above ... otherwise, it would work just fine on windows too.

**Comment by xmatthias** [comment]
- and THIS is why you should not do a PR from the master / develop branch - but use a feature branch :laughing: 

Please open the PR again once you have time for the documentation part (and use a dedicated feature-branch this time please) ;)

**Comment by Corfucinas** [comment]
Damn bots...

**Pull request closed without merging**
