### PR TITLE
List pairs (markets) subcommand(s)

### PR DESCRIPTION
**Pull request by hroff-1902**
Examples of usage (first part of logs cleared for readability):

```
$ ./freqtrade/main.py list-pairs --print-list --quote-currency USDT
...
2019-07-01 14:40:00,347 - freqtrade.exchange.exchange - INFO - Using Exchange "Bittrex"
Exchange Bittrex has 37 pairs with USDT as quote currency: ['ADA/USDT', 'ATOM/USDT', 'BAT/USDT', 'BCH/USDT', 'BSV/USDT', 'BTC/USDT', 'BTT/USDT', 'DAI/USDT', 'DASH/USDT', 'DCR/USDT', 'DGB/USDT', 'DOGE/USDT', 'ENJ/USDT', 'ETC/USDT', 'ETH/USDT', 'GRIN/USDT', 'LTC/USDT', 'NEO/USDT', 'NPXS/USDT', 'NXT/USDT', 'OCEAN/USDT', 'OGO/USDT', 'OMG/USDT', 'ONT/USDT', 'PAX/USDT', 'PMA/USDT', 'RVN/USDT', 'SC/USDT', 'TRX/USDT', 'TUSD/USDT', 'VDX/USDT', 'XLM/USDT', 'XMR/USDT', 'XRP/USDT', 'XVG/USDT', 'ZEC/USDT', 'ZRX/USDT'].
```

```
$ ./freqtrade/main.py list-pairs --exchange bitmex --print-list --quote-currency USDT
...
2019-07-01 14:41:10,136 - freqtrade.exchange.exchange - INFO - Using Exchange "BitMEX"
Exchange BitMEX has 0 pairs with USDT as quote currency.
```

```
$ ./freqtrade/main.py list-pairs --exchange bitmex --print-list --quote-currency USD
...
2019-07-01 14:41:16,432 - freqtrade.exchange.exchange - INFO - Using Exchange "BitMEX"
Exchange BitMEX has 2 pairs with USD as quote currency: ['BTC/USD', 'ETH/USD'].
```

```
$ ./freqtrade/main.py list-pairs --exchange bitmex --quote-currency USD
...
2019-07-01 14:43:05,422 - freqtrade.exchange.exchange - INFO - Using Exchange "BitMEX"
| Id     | Symbol   | Base   | Quote   | Active   |
|:-------|:---------|:-------|:--------|:---------|
| XBTUSD | BTC/USD  | BTC    | USD     | Yes      |
| ETHUSD | ETH/USD  | ETH    | USD     | Yes      |
```

```
$ ./freqtrade/main.py list-markets --exchange bitmex --quote-currency USD
...
2019-07-01 14:43:48,765 - freqtrade.exchange.exchange - INFO - Using Exchange "BitMEX"
| Id       | Symbol   | Base   | Quote   | Active   |
|:---------|:---------|:-------|:--------|:---------|
| .XBT     | .XBT     | BTC    | USD     | No       |
| .XBT30M  | .XBT30M  | BTC    | USD     | No       |
| .BXBT    | .BXBT    | BTC    | USD     | No       |
| .BXBT30M | .BXBT30M | BTC    | USD     | No       |
| .BETH    | .BETH    | ETH    | USD     | No       |
| .BETH30M | .BETH30M | ETH    | USD     | No       |
| XBTUSD   | BTC/USD  | BTC    | USD     | Yes      |
| XBTU19   | XBTU19   | BTC    | USD     | Yes      |
| XBTZ19   | XBTZ19   | BTC    | USD     | Yes      |
| ETHUSD   | ETH/USD  | ETH    | USD     | Yes      |
```

```
$ ./freqtrade/main.py list-markets --exchange bitmex --quote-currency USD --active-only
...
2019-07-01 14:44:45,322 - freqtrade.exchange.exchange - INFO - Using Exchange "BitMEX"
| Id     | Symbol   | Base   | Quote   | Active   |
|:-------|:---------|:-------|:--------|:---------|
| XBTUSD | BTC/USD  | BTC    | USD     | Yes      |
| XBTU19 | XBTU19   | BTC    | USD     | Yes      |
| XBTZ19 | XBTZ19   | BTC    | USD     | Yes      |
| ETHUSD | ETH/USD  | ETH    | USD     | Yes      |
```

```
$ ./freqtrade/main.py list-markets --exchange bitmex --quote-currency USD --base-currency BTC
...
2019-07-01 14:45:44,629 - freqtrade.exchange.exchange - INFO - Using Exchange "BitMEX"
| Id       | Symbol   | Base   | Quote   | Active   |
|:---------|:---------|:-------|:--------|:---------|
| .XBT     | .XBT     | BTC    | USD     | No       |
| .XBT30M  | .XBT30M  | BTC    | USD     | No       |
| .BXBT    | .BXBT    | BTC    | USD     | No       |
| .BXBT30M | .BXBT30M | BTC    | USD     | No       |
| XBTUSD   | BTC/USD  | BTC    | USD     | Yes      |
| XBTU19   | XBTU19   | BTC    | USD     | Yes      |
| XBTZ19   | XBTZ19   | BTC    | USD     | Yes      |
```

```
$ ./freqtrade/main.py list-pairs --exchange bitmex --quote-currency USD --base-currency BTC
...
2019-07-01 14:46:33,915 - freqtrade.exchange.exchange - INFO - Using Exchange "BitMEX"
| Id     | Symbol   | Base   | Quote   | Active   |
|:-------|:---------|:-------|:--------|:---------|
| XBTUSD | BTC/USD  | BTC    | USD     | Yes      |
```

```
$ ./freqtrade/main.py list-pairs --exchange bitmex --quote-currency USD --base-currency BTC --print-list
...
2019-07-01 14:47:12,832 - freqtrade.exchange.exchange - INFO - Using Exchange "BitMEX"
Exchange BitMEX has 1 pair with BTC as base currency and with USD as quote currency: ['BTC/USD'].
```

Open issues and TBD points will be submitted below. (so don't merge yet)

### CODE REVIEW

**Comment by hroff-1902** [comment]
* The `plural()` function (added to `freqtrade/misc.py`) has interface similar to the Wikimedia's `plural` magic word. Can be used in other places for better user experience.

**Comment by hroff-1902** [comment]
* The `get_markets()` (`freqtrade/exchange/exchange.py`) method will also be used in the fix for #1861 (select pairs with stake_currency as quote_currency).

**Comment by hroff-1902** [comment]
In the examples above (on BitMEX) not all markets are pairs, as you can see. The rest on BitMEX are either indices (those that are non-active) or futures (active). In the implementation of this PR, the pairs are separated from the rest of the market symbols by checking for `/` in the market symbol.

(BTW, as BitMEX has tradable futures, this will allow intra-exchange arbitrage strategies when this exchange will be supported)

**Comment by hroff-1902** [comment]
TBD:

* The `--active-only` option can be renamed to `--active`, `--only-active` (I'm thinking about this one), `--print-only-active`, `--print-active-only`.

**Comment by hroff-1902** [comment]
TBD:

* An additional `--pairs-only` (`--only-pairs`, `--print-pairs-only`) option can be added for the `list-markets` subcommand. With this, we could say for the `list-pair` subcomand that it's an equivalent to `list-markets --pairs-only`. It's not hard to implement, but will probably make the cli interface more flexible and straight.

**Comment by hroff-1902** [comment]
TBD: handling of default config.

In the meantime, the default config is fetched and validation fails if the exchange specified with `--exchange` does not have some of the pairs, specified in the `pair_whitelist`. We should define, how to handle default config for this subcommand (and others similar). This is discussed in #1945, let's move this discussion there.

**Comment by hroff-1902** [comment]
TBD: logging.

I'll submit a separate issue on this, since it's a general issue.

**Comment by hroff-1902** [comment]
TND: format of tabular output.

Now the tabular is used to print the table in the format, which is also used in the backtesting module.

I left for a while in the utils.py old code commented out that printed the tables in the format similar to the original `scripts/get_market_pairs.py` script. You can uncomment it to see the output in other format. However, I guess that tables should be printed in the same format in the different freqtrade modules and subcommands.

This is just to discuss it explicitely...

**Comment by hroff-1902** [comment]
TODO:

Tests:
* Tests for `plural()`;
* Tests for `get_markets()`;
* Tests for the `list-pairs` and `list-markets` subcommands;

**Comment by xmatthias** [comment]
> TBD: logging.
> I'll submit a separate issue on this, since it's a general issue.

What exactly is an issue with logging ... ? 

That's a ton of comments ... 

One early coment from my side:
 `--print-list` should print it in a json-friendly format (with double-quotes, ideally one below the other) we can copy/paste this directly to the pairs_list.

You should be able to archive this by using `json.dumps()` ...

**Comment by hroff-1902** [comment]
> One early coment from my side:
> `--print-list` should print it in a json-friendly format (with double-quotes, ideally one below the other) we can copy/paste this directly to the pairs_list.
> 
> You should be able to archive this by using `json.dumps()` ...

Nice point. Probably, this should be yet another format for printing the data. So introducing a switch, something like `--print-format=list/tabular/csv/json` would be better here... What do you think?

**Comment by hroff-1902** [comment]
> What exactly is an issue with logging ... ?

Do not remember this in the meantime... 🤣 

I'll pick some ideas from here (print json for example) to the new PR, #2370

**Comment by hroff-1902** [comment]
There is no reason to have it open anymore.
Closing in favor of #2370

**Pull request closed without merging**
