### PR TITLE
Dask multithreading analysis

### PR DESCRIPTION
**Pull request by Axel-CH**
!!!DON'T MERGE YET!!! Because of [This issue](https://github.com/dask/distributed/issues/2068)
## Summary
PR to improve freqtrade speed by taking advantage of multithreading with Dask distributed Framework

Solve issues: #746 and #1170

## Quick changelog
- Add Multithreaded Loop in create_trade function
- Create function get_history_and_signal to send to Dask Client as individual Tasks
- Add basic test for dask client initialisation

## What's new?
This PR improve drastically dask speed to get Pairs Price data and analysis to react more quickly

## How It works

**Before**
The loop is totaly synchronous and execute task each after one.
freqtrade dask old loop

**After**
Dask shceduler dispatch work concurently on workers depending on their availability
freqtrade dask new loop

## Test 
**Parameters**
**30 pairs** in whitelist
Multithreading configured with **8 workers** as below:
`
"multithreading":{
        "enabled": true,
        "workers_number": 8
    }
`
**Results**
freqtrade speed comparison 7

### To Do
- [ ] Add more tests
- [ ] Improve stability

### What's next
- Compare Performance with and discuss about possibilities with [Async PR #1101](https://github.com/freqtrade/freqtrade/pull/1101), maybe combine both aspects: Async and Multithreading with Dask
- Implement the same logic for SELL, for the moment there is a bottle neck on processing current opened trades

### CODE REVIEW

**Comment by xmatthias** [comment]
added don't merge label for this:
> !!!DON'T MERGE YET!!! Because of [This issue](https://github.com/dask/distributed/issues/2068)

letme us know when you feel it's ready.

**Comment by Axel-CH** [comment]
I had the rate limit enabled now async fetching is blazingly fast I will update the PR description. Thanks

**Comment by mishaker** [comment]
@Axel-CH thanks for your benchmark ! 
Do you think Dask is still necessary given that async is faster ? 
Maybe we can instead put time to extract all IO Bound processes in FT and async refactoring them ?

**Comment by Axel-CH** [comment]
Hi @mishaker It's a good question that i'm also asking myself. For me the point of using Dask is to be able to perform concurrent "get_signal" compute. Because in my stategy it takes 1s for each pair. If we can do that without using Dask and only with asyncio it's a good solution for me, knowing that I found memory stability Issues with Dask.
Do you think it's possible to perform concurrent "get_signal" compute with asyncio?

**Comment by xmatthias** [comment]
Asyncio is not "really" parallel - but utilizes waits for resources (mainly disk and network).

As computing indicators is (probably?) very cpu heavy - i am not so sure if async will help a ton (it will help a ton to not download last-tick as we do now ... but not if you drilled down the bottleneck to `get_signal`).

However it's tough tell for sure without having tried - i don't have that much experience with asyncio

**Comment by mishaker** [comment]
@Axel-CH asyncio doesn't help with cpu bound processes (at least it is not designed for). 
So I think for your scenario Dask could be helpful but I am not sure.
Do you think you can do another PR on top of the current dev branch for Dask? that way you will have asyncio already and will see if it helps. 
If you are ok for another PR maybe we can close this one?

**Comment by xmatthias** [comment]
i think doing a `git rebase` (resolving eventual conflicts) and  `git push -f ` will accomplish the same while keeping this PR and the good discussions in it ...

**Comment by Axel-CH** [comment]
@xmatthias @mishaker  no problem I will update this PR from develop. What I plan to do is to add the Dask layer just after the async candle fetching. Whe will be able to see if there is a performance improvement on the overall loop execution

**Comment by mishaker** [comment]
@Axel-CH any news on that? :) your code seems really interesting. if we can have a benchmark it would be great but no rush ;)

**Comment by Axel-CH** [comment]
@mishaker I plan to send an update this week-end. I was focused on my strategy because for the moment improving the speed of feqtrade will improve the speed of me losing money lol

**Comment by mishaker** [comment]
@Axel-CH any news on this one? if not do you mind if I close it ?

**Comment by Axel-CH** [comment]
@mishaker you can close this pull request for the moment. I'm currently focus on building my model. I'll switch back to this optimisation part after, Regards Axel.

**Pull request closed without merging**
