### PR TITLE
This adds stake amount in base currency to the RPC status message 

### PR DESCRIPTION
**Pull request by mishaker**

### CODE REVIEW

**Comment by hroff-1902** [comment]
But what if staking currency is the quote currency for the pair on an exchange?

(Example: XBTUSD (BTC/USD) pair on BitMEX, staking currency is USD, wallet used -- in BTC)

**Comment by xmatthias** [comment]
The bot does not support that at the moment anway ... 
and BitMEX is not on the list of supported exchanges ...

**Comment by hroff-1902** [comment]
> The bot does not support that at the moment anway, rpc is the least of the problems in that regard.
> and BitMEX is not on the list of supported exchanges ...

The freqbot/configuration.py says it's in the list of supported exchanges:
```
The following exchanges are supported: ... bitmex, ...
```
😃 

Seriously, I know that perfectly and you know that I'm working on support for this exchange which is prety far... So please do not reject any changes or enhancements simply because they will help support other exchanges in the future and seem usefuless for currently supported exchanges...

Thanks for explaining, I thought among currently supported exchanges (binance, bittrex, kraken (?)) there are some that can have staking in quote currency at least for some pairs. Definitely, RPC message is not the first issue here, sure. I just asked 'what if'.

**Comment by xmatthias** [comment]
I will not block support for other exchanges - by far.
but i'll also not block changes because it could cause a problem for an exchange we don't currently support until it's supported / proven to be working.

I don't know of any with inversed stakes but i'm happy to be proven wrong (however they still would not work on freqtrade... however IF we tackle pair-handling differently, then as it's own PR as that'll touch everything ...

**Pull request merged**
