### PR TITLE
New release - 2019.11

### PR DESCRIPTION
**Pull request by xmatthias**
## Summary
New Release 2019.11

Based on top of #2641

## Important
This release contains breaking changes to the freqtrade command line interface

* Freqtrade will now require an explicit sub-command. All parameters need to be **after** this sub-command:

#### Examples

`freqtrade --config customconfig.json --strategy AwesomeStrategy backtesting` will become `freqtrade backtesting --config customconfig.json --strategy AwesomeStrategy`

`freqtrade --config customconfig.json  --strategy AwesomeStrategy` will become `freqtrade trade --config customconfig.json --strategy AwesomeStrategy `

Trading/dry-run-mode is available  as `freqtrade trade`.

`--custom-hyperopt` is replaced by `--hyperopt` and does not default to `DefaultHyperopt` anymore.

Strategies need to be explicitly defined and do not fall back to DefaultStrategy anymore.
You can specify this either via `--strategy AwesomeStrategy`, or in the configuration (`"strategy": "AwesomeStrategy"`).

## Highlighted Changes

* Introduction of `trade` subcommand (Read below for further info)
* Introduction of `new-strategy` and `new-hyperopt` subcommands to simply create new strategies and hyperopt files.
Please refer the documentation for full usage samples [new-strategy](https://www.freqtrade.io/en/latest/utils/#create-new-strategy), [new-hyperopt](https://www.freqtrade.io/en/latest/utils/#create-new-hyperopt).
* Support for logging to syslog and journald.
* Addition of `/show_config` command to rpc methods to quickly see the bot's most important configurations.
* Addition of `--dry-run` flag to force trades to be simulated, overriding the corresponding configuration value.

#### Pairlists
* Deprecation of `pairlist` in the configuration - which is replaced by `pairlists` - a list of different pairlist configurations.
* Introduce a new way to chain different pairlists and filters dynamically [Detailed pairlist documentation](https://www.freqtrade.io/en/latest/configuration/#pairlists).
* Introduction of `test-pairlist` subcommand to test the result of the new pairlist chaining.
* Introduction of a low-price filter (requiring 1pip to be > N%).

#### Hyperopt
* Introduction of `hyperopt-list` and `hyperopt-show` subcommands.
Please refer the documentation for full usage samples [hyperopt-list](https://www.freqtrade.io/en/latest/utils/#list-hyperopt-results), [hyperopt-show](https://www.freqtrade.io/en/latest/utils/#show-details-of-hyperopt-results).
* Introduction of new `trailing` hyperopt space for optimizing trailing stop parameters. See [Understand Hyperopt Trailing Stop results](https://www.freqtrade.io/en/latest/hyperopt/#understand-hyperopt-trailing-stop-results).

## Full changelog:

```
2f76eaf3 minor: Fix documentation formatting
18c73ceb Add tests for the last commit
8431b54b Fix index limits handling
5fc357ee Fix typo
a9f7e9fb Fix NO_CONF; fix tests
081b21fe Bump colorama from 0.4.1 to 0.4.3
ed053d24 Bump ccxt from 1.20.22 to 1.20.46
0ca3157a Bump coveralls from 1.8.2 to 1.9.2
49344567 Bump mkdocs-material from 4.5.0 to 4.5.1
0f4dcaa4 Bump pytest-mock from 1.12.1 to 1.13.0
4b560880 Add tests for hyperopt-list, hyperopt-show
21c68557 Build latest along with develop image
ed7207d4 Show pairs which are wrong ...
bb9235c7 Validate stake-currency against pairlist - making sure only correct pairs are in the whitelist
2bd4008c fix space name ...
d21ae4ed Add fixes for comments in the review
1da008b3 Document "quick" hyperopt of roi/stoploss and trailing stoploss
703458f3 Add test for loading ticker-interval from strategy
4b0a4c93 Fix hyperopt with ticker_interval from strategy
216094a7 Add reference to hyperopt-list and hyperopt-show to the Hyperopt doc
4efd8b96 Add description for hyperopt-list and hyperopt-show to the docs
b61f4383 Make flake happy
b20bea84 Adjust tests
54694dd3 Manual merge of some conflicts in hyperopt
16a50fbe Resort documentation
51f074ba Don't print quote-currency for -1
0ba804d0 Address first part of feedback
8a7fe3f1 The file will (for users) be in user_data - just in the repo it's in templates
054484ad load_pair_history should not return None, but an empty dataframe if no data is found
ac3e0615 Resolve issues stated in the review
ddf86d63 Adjust docs index
ba29a2ff Move docs on loss function creation to a separate doc file
b33e47a4 Update documentation with test-pairlist
298e8b23 Add testcase for test_pairlist
17e03559 minor: fix typo in docs
cd20d5b5 Update kraken pairlist
ebf6dad3 Update binance pairlist default config
683406b5 correct fallback to stake_currency
fc7b9846 Bump mypy from 0.740 to 0.750
110fbd3f Bump ccxt from 1.19.86 to 1.20.22
f0428be9 Bump pytest from 5.3.0 to 5.3.1
0b03c6c7 Implement to json
150a497c output pairlist after fetching all
ee733210 minor: Fix formatting typo in docs
86342efa Adjust test
05967442 Adjust test
d6b58767 Adjust test
668d4244 Refactor log_trials_result()
32c9b5f4 Description for generate_roi_table reformulated slightly
f42ce8fc Fix typo in the docs
26a7af85 Add trailing_space() into AdvancedSampleHyperOpt
f862b4d0 Add description for 'default' space
a88bfa8d Fix: trailing_stop_positive should be positive
fffd47e3 Add description of trailing space into docs
7a3c3c4d Add directlink to the section
eafccb44 Add command sample for journalctl with -u
b040cbff syslog and journald cases splitted
15343456 Add test_pairlist method
8f9b5095 Fix some tests
c3d74116 Fix imports
997c4262 fix some datatypes
111f018c Add datatype to configuration documentation
64da8771 Update stake_amount description
f0e6a9e0 Address feedback
a373e489 Comment added
f2cd4fda Fix the rest of tests
8e751216 Add hyperopt-list and hyperopt-show commands
cceb00c4 Try coveralls
585b8332 Improve tests and unify required attribute
066f3240 Make flake happy
8e1e20bf Fix some tests
0ac592ad Fix markets in conftest
17269c88 Fix _get_min_pair_stake_amount()
82041073 Add test for get_min_pair_stake_amount() with real data
9e7d367b Realign strategy_override paramters
12b9257c new-lines before defaults in documentation
37f698d9 move default values to Description field
e7c17df8 validate defaults in documentation
418ca003 Bump jsonschema from 3.1.1 to 3.2.0
03f02294 Bump pytest from 5.2.4 to 5.3.0
0a7a1290 Bump pytest-mock from 1.11.2 to 1.12.1
28f73ecb Bump ccxt from 1.19.54 to 1.19.86
6ab7f93c Bump scipy from 1.3.2 to 1.3.3
d1511a10 Update some config documentation
0775ac08 Cleanup constants and required
646a9d12 Align quoting of json schema
e7be742c Run validation after custom validations
8d002a8f Fix some more tests
af3eea38 Move config json validation to after strategy loading
4dc0631a Lower minimum tradeable value
a3415e52 Fix some test-types
1b337fe5 Remove unnecessary code piece
50350a09 use wallets instead of doing a direct call to /balance
1bf8d8cf show /balance in stake currency
62d50f51 add tests for balance from get-tickers
8c64be3c get tickers only once to show balance
a374df76 some minor fixes from feedback
cbf710a4 Fix coveralls (?)
f05818a8 Allow transition from "no-config"-pairlist to pairlists
63ad95a4 reenable slack
5fb14e76 Adjust folder to match user_data folder - otherwise running tests creates this folder
c7c7a1c2 skip test due to no journald installed
1242263d Make test OS dependent
31c598f8 Add tests for advanced logging setup
6cb48305 Testcase added
067267f4 Log messages improved (plural/singular)
99db5341 Tests adjusted
737c07c5 Make mypy happy
097cdcb5 Save epochs at intermediate points
175591e5 Fix test
a183162d Add description into Advanced Setup section
a6bb7595 Update utils doc
210d468a Reinstate mfi ...
5f8fcebb Parametrize hyperopt file
f23f659a Use strings instead of subtemplates
f26c4008 Allow selection of templates for strategy
b3dbb818 Add subtemplates
5e5ef21f Align example imports
be4a4180 Use single line comments for samples
f7322358 Update documentation
671b98ec Fix windows test
ed04f7f3 Create userdir and backtest SampleStrategy
cbb187e9 Use constant for Strategy and hyperopt userdirpaths
03cdfe8c Add tests for new-hyperopt
37f81394 Small stylistic fixes
79891671 Adapt after rebase
65489c89 Add no-arg test
b36a1d32 test new_stratgy
8a1d02e1 Update numpy imports in sample strategies
8c2ff2f4 Add template for new-hyperopt command
e492d476 Disallow usage of DefaultStrategy
98baae94 Add jinja2 to requirements
e3cf6188 Add first version of new-strategy generation from template
8cf8ab08 Add note about create-datadir to install instruction
ed1d4500 Update documentation for create-userdir util
41494f28 Allow resetting of the directory
19b1a6c6 create-userdir should create the notebooks folder, too
471bd4d8 Small stylistic fixes
084efc98 Address test-failures due to file moves
1d2ef5c2 Extract directory_operation tests to it's own test file
fd45ebd0 Copy templates when creating userdir
258d4bd6 move sample-files from user_data to templates folder
b8aa727e Fix second part of freqtrade-strategies #51
eac01960 Add testcase for empty-order case
a5bd4e32 improve cancel_order handling
9aac0804 Fix 'remaining' bug when handling buy timeout
8b639b50 Remove only :return:
5f88c4aa Add example of usage for Aroon, Aroon Oscillator
63399621 Improve commands help list
c92f233c Move settings to correct location
751157b4 Don't notify on builds from forks
5f62a9e4 rename ttl to refresh_period
a8855bf7 rename LowPriceFilter to PrieFilter
c22b00b3 move pairlist filters out of config[]
cd6d2761 Bump pytest from 5.2.2 to 5.2.4
dddccf8f Bump ccxt from 1.19.25 to 1.19.54
0bc71403 Bump mkdocs-material from 4.4.3 to 4.5.0
cb6b3e17 Bump tabulate from 0.8.5 to 0.8.6
e7157fad Bump python-rapidjson from 0.8.0 to 0.9.1
a33d4087 Bump plotly from 4.2.1 to 4.3.0
42474b71 Bump flake8-tidy-imports from 3.0.0 to 3.1.0
93356459 Bump sqlalchemy from 1.3.10 to 1.3.11
599e18b9 Bump urllib3 from 1.25.6 to 1.25.7
547d65b0 Fix broken test
e4e8a611 Add tests for telegram
2b190e56 Add documentation
acab5679 Add /show_config to telegram
2c976bdd Add show_config endpoint
3aee8d2b Improve rest api client / status response
b6a12044 seperate docs job
be53c088 Try moving coveralls to github actions
91047830 Add tst for worker termination
6e0655b3 add empty worker variable
edc0d7f2 Fix non-terminating bot
b167fb07 fix windows test
3b9899df hyperopts ...
f94d4631 update checkout action to pinned version
569a547b Update Actions CI to new subcommands
f9a92c28 Adjust test
ab194c7d Add test
38243c52 Filter open trades - they are not added to the profit calc
c8c48156 Don't load trades twice ...
68904296 Allow timeout of 0
6174a5dd Reimplement adjustment of ccxt 'has' with more generic ccxt_config class attribute
e26bbc7d Add fix for bibox exchange
62c1ff77 update action to 2.1.0
6ac73f7c Update missed strings
66619204 re-add hyperopts multiple ...
c42c5a1f Adjust "requires subcommand" message
5b62ad87 Remove hyperopts occurances
2eb65132 Improve timedout handling
c449e392 Replace more occurances of ticker_interval
1c57a4ac more replacements of ticker_interval
334ac8b1 Adapt documentation for timeframe
d801dec6 Some more places with ticker_interval gone
08aedc18 Exchange ticker_interval with timeframe in some more places
e4bdb925 Replace some occurances of ticker_interval with timeframe
11f7ab61 Remove decimal import from rpc
df9bfb6c Add FIAT currency to status-table
ab9506df simplify status_table command
136ef077 Add sleep to allow thread to start
e8a8f416 Update dockerhub description from github readme.md
8c76f450 Use correct dockerhub image name
96f550c6 Disable tests
37ef5c38 integrate Slack notification
52e24c3a Split error-messsage between incompatible and wrong stake amount
025350eb Fix typo in the rest-api docs
80099743 Update documentation
75d5ff69 Add ping endpoing
a241c2af Build macos - ...
d1729a62 fix windows build
e51a7201 Apply cache to pi image
ff1d3643 Add github actions action
031157f2 Bump numpy from 1.17.3 to 1.17.4
c65d217d Bump scipy from 1.3.1 to 1.3.2
0a13f7e1 Bump ccxt from 1.19.14 to 1.19.25
27d81bb6 minor: More cosmetics on Exchange Notes
95492958 wordings
661c8251 minor: Exchange notes docs
83067c1e minor: Fix link in the Faq docs
04b51a98 Include warning-message to bittrex explanation
e810597e Add restricted markets snippet to documentation
692d6afb Minor exchange notes typographical cosmetics
eba55c27 Change link
085aa308 Implement ticker caching
de2d04f0 Add note about systemd load location
12654cb8 Add seperate exchange section in docs
4b15873e Simplify examples
86a5dfa6 Update documentation
0b480083 update documentation
5caeca75 Improve tests for pairlist-sequence behaviour
7ff61f12 pass pairlist position into the pairlists
ae356493 improve pairlistmanager errorhandling
a01b34a0 tests
02b9da8a Update documentation
ed0c7a6a Update configschema to fit new pairlists approach
25cb935e Some more adjustments for new pairlist
c74d7662 move from name to name_list
37985310 remove cachetools dependency
c3b4a4dd Update sample configurations
d7262c0b Fix correct ticker type
870966dc Fix more tests
85beb3b6 Fix test
bf69b055 Add name getting
31c7189b Verify blacklist correctly
eaf3fd80 Allow blacklist-verification from all pairlists
10595862 Small adjustments
b610e8c7 Don't refresh tickers if they are not needed
e632720c Allow chaining of pairlists
1f042f5e Quick start and easy installation sections reworked
54b63e89 Wordings on top of #2495
31ab32f0 Always set trailing_stop=True with 'trailing' hyperspace
bc5c91f6 add missing note block
076ef040 git branch note explanation
b0150d54 remove not use statement
dd47bd04 Move description to correct place
da57396d Fix UTC handling of timestamp() conversation in fetch_my_trades
d3a37658 Fix test
f90676cf Add trailing stoploss hyperspace
ca77dbe8 Fix UnicodeError in hyperopt output
60109aaa Bump ccxt from 1.18.1346 to 1.19.14
28f0c002 Bump pandas from 0.25.2 to 0.25.3
bc78316a Bump flake8 from 3.7.8 to 3.7.9
b8a6c55b Bump arrow from 0.15.2 to 0.15.4
c8638ce8 Fix bug where bids_to_ask_delta causes doublebuys
eb0b0350 Introduce remove_credentials to remove code duplication
f6a66cd3 Fix typo
871019c8 docker doc update about restart policy
1e44f93c Fix pandas access warning
3eca8021 Don't check exchange for Utils commands
6550e1fa Change docstring  in sampleHyperopt
80ad37ad Updated plot_indicators test
3287cdd4 Improve documentation regarding loading methods from hyperopt
12e86ee4 Make travis test-hyperopt the sample strategy
97d0f93d Align samples (hyperopt and strategy) to work together
861f10dc Allow populate-indicators to come from strategy
e9af6b39 Fix typo
2124661c Update faq with examples of grepping the log
691cec79 Be more selective which startup-messages are shown
241d9475 Add new runmodes
a80e49bd Change level of rpi header
9a42afe0 Move exchange-constants and retriers to exchange.common
b6616d7a Add test helping debug #1985
7be378aa Remove markets mock where it's not needed
734a9d5d Seperate tests related to worker from test_freqtradebot
ce6b869f Cleanup test
dc5f1b28 Extract integration tests into sepearte file
5dcf28ca Reduce frequency of "startup-period" message
365a408d Update release-documentation to fit new release style
9e988783 Allow configuration of stoploss on exchange limit
bba8e614 Rename function in samples
ad98d619 Update developer docs
14758dbe Some small cleanups
d89a7d52 Document new method to configure filters
640423c3 Add config samples for chainable pairlist filters
fd9c0260 Introduce chainable PairlistFilters
44289e4c Allow not using files from user_dir
6928c685 Add documentation sample for parallel_trade_analysis
dd408aa5 Add analyze_trade_parallelism analysis function
dac88c6a extract Find parallel trades per interval
78fe5a46 Update travis to verify for correct title usage
7a96d3c9 Update raspbian install documentation
b7b1e66c Convert to % as part of RPC to allow users to use unrounded ratio
5ed77711 Update documentation to include get_trades
c2076d86 Use scoped_session as intended
b37c5e48 use get_trades in rpc modules
26a5800a Extract get_trades function
01efebc4 Extract query to it's own function
ab117527 Refactor get_best_pair to persistence
f20f5ceb Move performance-calculation to persistence
6fe7b13e Replace coins in whitelist with existing ones
9c180e58 Log to stderr
de2cc58b Final cleanups and added tests
d803d86f Add low_price_percent_filter
d706571e Extract precision_filter to seperate function
4ff03553 Simplify precision_filter code
466a3b87 Enhance tests to cover precision_filter correctly
069da224 Add test to verify this is correct
e82460bd Fix create_cum_profit to work with trades that don't open on candle opens
61c037f2 Fix some typos and comment mistakes
73343b33 Address feedback
3a6020dc small improvements to stoploss doc
596a269d Bump pytest from 5.2.1 to 5.2.2
44d0a6f2 Bump ccxt from 1.18.1306 to 1.18.1346
60b99469 Bump nbconvert from 5.6.0 to 5.6.1
46b975a4 Bump pytest-mock from 1.11.1 to 1.11.2
70ad909b change samples to python code, and simplify a few things
2af3ce3e Improve stoploss documentation - split out offset_is_reached
132a4da7 Small style fixes and adjusted tests
73f5bff9 Add validation to make sure strategies work on that exchange
223f0cd4 Apply startup_period to edge as well
c4cb098d Update documentation with indicator_startup_period
2bc74882 Add test for startup_candles
2ba38807 Fix small bugs
33164ac7 Refactor loading of bt data to backtesting ...
86624411 Test trim_dataframe
5cdae17d Add tests for timerange modifications
bd4a23be Refactor start-adjust logic to timerange
5c2682e2 Add startup_candle_count to sample strategy
6382a4cd Implement startup-period to default-strategy
704121c1 Move most logic to history
9c7696a8 Add required_startup to backtesting
9e7e051e add trim-dataframe method
616fe08b Add subtract_start to timerange object
141c4541 Add startup-candles-argument for strategy
e5487441 Fix typos
48d83715 Fix typo in docs (thanks to Escaliert@Slack)
8b4fea4b Update installation.md
13ae339a Improve windows Install documentation with hints
bf20f3b7 Remove part which is related to #2418
32df73c0 flake
ef1885c3 Fix more tests
f5351e60 Adjust markets mock
bfec9d97 docs: Create Advanced Post-installation Tasks section; move systemd stuff there
3a7553ee Adjust option helpstring
d0521d33 Refactor whitelist handling
ea6b94fd docs: add a tip for The Ocean exchange
2e896462 Fix wrong volumepairlist message
e6337798 Improve pairlist documentation
41f97a73 Add logging to syslog and journald
45b83cc5 Don't require pair_whitelist for dynamicPairlist usecases
b3e028e8 Improve dynamic pairlist documentation
13255b37 Allow non-config to parse config
e1edf363 Fix test failures
1c503f39 Handle some merge aftermaths
2d34c0f5 Update helpstring exports
6fb96183 Reword help string
a5c83b66 Add --dry-run to trade command
89283ef4 Rename --custom-hyperopt to --hyperopt
ff1fa17d No default value for the config parameter
08e6d8a7 Rollback defaulting to DefaultHyperOptLoss
c4105436 Disable defaulting to DefaultHyperOpts and DefaultHyperOptLoss
95299d94 Remove unused test line
b73426b9 Disable Defaulting to DefaultStrategy
52ff391c Default dockerfile to "freqtrade trade"
344a0a09 Update remaining documentations
27102263 Update documentation to use subcommands
381b0d3d Fix typo with new parser
52523bcd Use strategy child parser
0d13e2cb Update travis to run new methods
014881e5 Allow query version without subcommand
67b82638 Move test without command to test_main
09f18d07 Adjust some hyperopt tests
9ef874e9 Add Custom message during transition period
0aa73d5b Add test for failing case
ad2fa617 Fix utils test
e8106f37 Fix most tests to have trade as default argument
db3b9744 Fix calling sequence
d62a4d35 Fix some minor problems
1b25b5f5 Remove duplicate short-form `-s`
03add90c Adjust some tests to new call-method
0f2e277f Rename subparser variable to command
8664e7f7 Have main.py support only subcommand mode
cb37f432 Add trade subparser (and make subparser a requirement)
2a535b72 Parser should not have default
cd233688 Add first version with shared parent parsers
```

### CODE REVIEW

**Comment by hroff-1902** [comment]
2019.12? 
2019.11 was missed/skipped...

**Comment by hroff-1902** [comment]
The baseline (#2641) is okay...

**Comment by hroff-1902** [comment]
#### Hyperopt
* Introduction of `hyperopt-list` and `hyperopt-show` subcommands. 
Please refer the documentation for full usage samples [hyperopt-list](https://www.freqtrade.io/en/latest/utils/#list-hyperopt-results), [hyperopt-show](https://www.freqtrade.io/en/latest/utils/#show-details-of-hyperopt-results).
* Introduction of new `trailing` hyperopt space for optimizing trailing stop parameters. See [Understand Hyperopt Trailing Stop results](https://www.freqtrade.io/en/latest/hyperopt/#understand-hyperopt-trailing-stop-results)

**Comment by hroff-1902** [comment]
^^ All hyperlinks in the Release Notes should refer to correct branch of the docs, not to the latest one.

**Comment by xmatthias** [comment]
> 2019.11 was missed/skipped...

i did this intentionally to be honest ... this contains mostly changes done in november.
i can change it 2019.12 ...but keeping 2019.11 allows us to do another release late december...

**Comment by hroff-1902** [comment]
are you going to answer questions wrt new release during Xmas/new year holidays? 😁 
I propose for this release to be the last one this year...

**Comment by hroff-1902** [comment]
"Trading/dry-run-mode is available as `freqtrade trade` (uses dry-run/live-trade mode set in the config) or `freqtrade trade` (run in dry-run mode even if config sets live-trade)."

**Comment by hroff-1902** [comment]
Is it possible to save the Release Notes as a file somewhere in the repo to have an ability to add comments on it as on the docs files?

**Comment by xmatthias** [comment]
> "Trading/dry-run-mode is available as freqtrade trade (uses dry-run/live-trade mode set in the config) or freqtrade trade --dry-run (run in dry-run mode even if the config sets live-trade)."

way too complicated and confusing for a release log. `freqtrade trade` replaces the former command of `freqtrade` ... yes we have `--dry-run` too now - but that's not related to getting the bot updated - and is not to be listed as breaking change.
I'll add the --dry-run as seperate change.

**Comment by hroff-1902** [comment]
Edited (slightly) the initial post, mostly cosmetics after you added all the above.

**Pull request merged**
