### PR TITLE
Update CI to run on python 3.10

### PR DESCRIPTION
**Pull request by xmatthias**
## Summary
Ci to python 3.10, as it's now released.

### CODE REVIEW

**Comment by xmatthias** [comment]
Currently blocked by https://github.com/PyTables/PyTables/issues/909

**Review by ghost — APPROVED** [review]
>

**Comment by samgermain** [comment]
`asyncio.get_event_loop()` is deprecated in python3.10, I saw it in `exchange.refresh_latest_ohlcv`

https://docs.python.org/3/library/asyncio-eventloop.html

**Comment by xmatthias** [comment]
as long as pytables is not updating, installation is impossible on 3.10 anyway - so I'm honestly not too worried about that at this point.
Also, deprecated means we should get rid of it before 3.11 ... which is still more than a year in the future ;)

**Pull request merged**
