### PR TITLE
Dry run order filling

### LINKED ISSUE #3389: Take a 'realist' filled price in dry run for market orders (compute using order book and the stake amount)
### Story like :

As a trader
I want the dry run to be closed to real money behavior
So that i can make a choice on number of asset i trade with (depends liquidity).

### Further explanations:

What about compute the average filled price (as it is a market buy and market sell) using the order book and taking into account the stake_amount ?

Then this average filled price is used to compute profit.

### The snippet :

```
def forecast_avg_filled_price(self, action, stake_amount, orderbook) -> float:
        
        book_entry_type = None
        if action == 'buy':
            book_entry_type = 'asks'
        if action == 'sell':
            book_entry_type = 'bids'
        
        remain_amount_to_be_filled = stake_amount
        filled_amount = 0
        for book_entry in orderbook[book_entry_type]:
            book_entry_price = book_entry[0]
            book_entry_coin_volume = book_entry[1]
            book_entry_ref_currency_volume = book_entry_price * book_entry_coin_volume
            if remain_amount_to_be_filled > 0:
                if remain_amount_to_be_filled < book_entry_ref_currency_volume:
                    filled_amount += remain_amount_to_be_filled * book_entry_price
                else:
                    filled_amount += book_entry_ref_currency_volume * book_entry_price
                remain_amount_to_be_filled -= book_entry_ref_currency_volume
                # print(' {} : book_entry price : {} with ref volume {}'.format(action, book_entry_price, book_entry_ref_currency_volume))
                # print(' {} : remain_amount_to_be_filled {} '.format(action, remain_amount_to_be_filled))
            else:
                break
        forecast_avg_filled_price = filled_amount / stake_amount
        return forecast_avg_filled_price
```
Have a nice day.

### PR DESCRIPTION
**Pull request by xmatthias**
## Summary
Revisit dry-run order filling.

closes #3389

## Quick changelog

- Take a an average price for market orders based on current orderbook-volume of the first 20 Orderbook slots
- don't auto-fill limit-orders, but wait until the price reached the desired fill price

### CODE REVIEW

**Comment by rokups** [comment]
Im dry-running this but now im not sure there is a point. Using this config:
```json

    "bid_strategy": {
        "price_side": "ask",
        "ignore_buying_expired_candle_after": 120,
        "use_order_book": false,
        "ask_last_balance": 0.0,
        "order_book_top": 1,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
    "ask_strategy":{
        "price_side": "bid",
        "ignore_buying_expired_candle_after": 120
    },
    "order_types": {
        "buy": "market",
        "sell": "market",
        "stoploss": "market",
        "forcesell": "market",
        "stoploss_on_exchange": false
    },
```
Will dry run with such config be of any use?

**Comment by xmatthias** [comment]
For sure (althoug it'll heavily depend on your stake amounts).

As you're using market orders, the orders should fill "slightly higher" (compare open_rate_requested with open_rate in the database) - as it'll consider the volume on the orderbook at that moment.

you'll probably not see much impact with 20$ stakes - but with 1000$ or so , you should (potentially / hopefully) see some difference.

**Comment by rokups** [comment]
Stake is exactly 1000 USDT. Is relevant information logged to the log file so we can gauge impact of this branch?

**Comment by xmatthias** [comment]
no - but you'll be able to see it in the database by comparing `open_rate_requested` with `open_rate` (currently, these 2 will be identical in dry-run - which will not be the case with this PR).

**Comment by rokups** [comment]
This dry has been running for couple weeks now. See if you can find what you were looking for.
[tradesv3.dryrun.CHTP_v9_mod-kucoin.sqlite.zip](https://github.com/freqtrade/freqtrade/files/6709447/tradesv3.dryrun.CHTP_v9_mod-kucoin.sqlite.zip)

**Comment by xmatthias** [comment]
Absolutely that's exactly what i needed. 
you've had an average slippage of ~0.13% (0.14% on buy, and 0.10% on sell) - which i guess is in the expected range for ~1600$ trades.

``` sql
select avg(open_diff_rel), avg(close_diff_rel) 
from (
select open_date, open_rate, open_rate_requested,
open_rate_requested  - open_rate open_diff,
(open_rate - open_rate_requested ) / open_rate * 100 open_diff_rel, 
close_rate, close_rate_requested,
close_rate_requested - close_rate close_diff,
(close_rate - close_rate_requested ) / close_rate * 100 close_diff_rel, 
close_profit_abs 
from trades
);
```

i assume there's not been any problems or so because of this?

**Comment by rokups** [comment]
Not that i have noticed, everything seems to be in order

**Pull request merged**
