### PR TITLE
featherdatahandler: implement trades_store/_trades_load

### PR DESCRIPTION
**Pull request by TheJoeSchr**
as discussed on discord. for now it's implemented using pandas functions. I haven't tested it against a big backtesting, but it's better than not existing

### CODE REVIEW

**Comment by TheJoeSchr** [comment]
I was thinking, in most usecases we will convert to pandas DataFrame eventually, so we can't overcome this memory load anyways. Maybe it would be better to accept it and rewrite the interface to use DataFrame. That way we don't duplicate the trades as `List` and as `DataFrame`

**Comment by xmatthias** [comment]
> in most usecases we will convert to pandas DataFrame eventually, 

That's true for converting to ohlcv ... but it's clearly not true for downloading trades data (which is the only case where we actually SAVE the dataframe) - where appending to a list has big benefits over appending / concatenating dataframes.

**Comment by xmatthias** [comment]
@TheJoeSchr anything that's preventing this from being "no longer a draft" ? 

i think the PR is actually mostly fine (i've reverted a few non-related formatting changes ..)

**Comment by TheJoeSchr** [comment]
@xmatthias no it's fine from my point of view. I thougt I needed to do a big test and never got the time. But it works and is significantly faster on my usecases than hdf5, so ready to merge

**Review by xmatthias — APPROVED** [review]
great - then let's have this ;) 

as you correctly pointed out "somewhere" - it's the same approach we use with hdf5 - which is also converting it to a dataframe before writing / after reading.
As such, it'll just give us the feather performance - without drawbacks on top of hdf5.

LGTM :+1:

**Pull request merged**
