### PR TITLE
Add price jump warning

### LINKED ISSUE #7407: Backtesting with missing candels and 1000% higher price afterwards
======== SUMMARY METRICS ======
| Metric                      | Value                      |
|-----------------+--------------|
| Starting balance          | 1000 BNB           |
| Final balance               | 8859.982 BNB    |
| Total profit %              | 786.00%             |

So much profit.... It's because of missing candles

image

**How can I avoid this problem in backtesting?** 
If I have an open position, the candels are missing, afterwards the price is 1000% higher than before.

### PR DESCRIPTION
**Pull request by xmatthias**
## Summary

Add price jump warning - alerting people about potential unrealistic gains.

Closes #7407

## Quick changelog

- price jump warning

### CODE REVIEW

**Review by robcaulk — COMMENTED** [review]
Just curious, but are we adding unnecessary overhead with this? We expect this to be hit 0.01% of the time, or less. People trading established pairs wouldn't need it at all, right?

**Comment by xmatthias** [comment]
> Just curious, but are we adding unnecessary overhead with this? We expect this to be hit 0.01% of the time, or less. People trading established pairs wouldn't need it at all, right?

"established pair" is a broad term ...

also an established pair could have a token swap - think SHIB - it's kinda been around a while now - but it's surely possible that at some point, they decide "we have too many 0 in our number - so let's exchange all tokens at 1000:1 - which would effectively boost price by 1000%.
freqtrade won't have this info - so would assume that that pair just spiked 1000%

it's an edgecase, sure - but one nobody will be checking for while backtesting, while it'll greatly exaggerate wins (though you should notice if 1 pair has a 1000% trade).

I'm not against ignoring this request entirely (closing this and the corresponding issue as won't fix) - as it's an edge-case that WILL show up in backtesting as "very high fluke" the moment you look at any other metric than "total profit"

---

it's also not "really" relevant for live - so maybe moving this to the datahandler (so it only runs on data we load from disk) would make more sense?

**Review by robcaulk — APPROVED** [review]
LGTM

**Comment by popperwin** [comment]
Hello!
Thanks for this feature, it can be useful. 
However I was backtesting on ETH/USDT on binance for year 2022, and I had a price jumps warning without any "Missing data fillup".

I looked at the code and it seems that the condition `warn_price`  in the function `_check_empty_df` doesn't apply the timerange selected; so the warning is triggered even if the price gap is not in the timerange of the backtesting.  The warning can be very misleading in that cases.
 
In my case the drop were between  `2017-08-22 03:55:00`  to `2017-08-22 04:00:00`, but my backtest timerange is from `2022-01-01` to `2022-12-31`

**Comment by xmatthias** [comment]
nice spot - will be updated shortly.

**Pull request merged**
