### PR TITLE
remove populate_any_indicators

### PR DESCRIPTION
**Pull request by robcaulk**
We have planned for deprecation of the `populate_any_indicators()` starting March 1st, 2023. Here we remove the functionality and raise an operational exception for any users trying to use the old function.

### CODE REVIEW

**Comment by tomjrtsmith** [comment]
What's the history here? Is it necessary to remove it if it's just going to mess up a whole lot of people's strategies? Is it replaced by populate_indicators?

**Comment by xmatthias** [comment]
@tomjrtsmith 
we have a [migration guide](https://www.freqtrade.io/en/stable/strategy_migration/#freqai-strategy) which will show you how to migrate.
The method was deprecated in 2023.1 (including a noisy DEPRECATION WARNING if used in a strategy) - and will be removed with 2023.3 (we'll not merge this PR until the 2023.2 release - which will most likely happen sometime later this week).

there's little point in keeping methods around we know cause lookahead biases in backtesting (and potentially other problems).

**Review by wagnercosta — APPROVED** [review]
LGTM :+1:

**Comment by xmatthias** [comment]
it absolutely does! 
Will be merged right after the new release :+1:

**Pull request merged**
