### PR TITLE
Don't compare floats when updating fees

### PR DESCRIPTION
**Pull request by xmatthias**
## Summary
As reported on slack, sometimes the amount does not match if an order is filled in multiple trades, and the sum results in a float rounding error.

This can be easily solved by using `math.isclose()` - however since we can have very small numbers, we should set `rel_tol` to a lower floating point to avoid calculation problems.

part of the issue: #1639 (will probably not cover all of it, since this looks at this specific problem).

## Quick changelog

- Add tests to verify this problem and make sure this won't break in the future
- introduce `MATH_CLOSE_PREC` constant - to have one place to specify this rounding
- use math.isclose() to compare amounts

### CODE REVIEW

**Comment by hroff-1902** [comment]
Need to study PEP0485 https://www.python.org/dev/peps/pep-0485/ first in details, it contains wide retrospective on the theory behind and approach implemented in python ("Behavior near zero", "How much difference does it make?")...

**Comment by xmatthias** [comment]
It's better to use this link (or the asnwer in it): https://stackoverflow.com/questions/5595425/what-is-the-best-way-to-compare-floats-for-almost-equality-in-python/33024979 - which lists the equivalent for older python versions.

For developers, the code is sometimes easier to interpret ... 

https://github.com/python/cpython/blob/6b5f1b496f0b20144592b640b9c975df43a29eb0/Modules/mathmodule.c#L2784-L2825

**Comment by hroff-1902** [comment]
should not the precision 1) be abs_tol 2) be a precision for the currency from the ccxt exchange data?

**Comment by xmatthias** [comment]
no, i don't think so.

keep in mind that we're trying to fix a floating point rounding error, not a calculation error on either side - these don't appear "early" in the decimal places - at least i've never seen that. 

Taking your example from #1639:
```
print(format(0.3 - 0.1 - 0.1 - 0.1, '.20f'))
-0.00000000000000002776
```

the result is not 0.0 - however, the roundin error happens after 16 zeros - not after 8 or less.

## For this specific usecase:
taking binance as example (since i know the problem there best):

assume we buy amount 10 of currency XXX, which has a lotsize of 0.1.

Binance will take the fee either from BNB (which is no problem) or from the "target" currency, XXX in this case, subtracting this fee from my requested amount of 10.
Now the fee will not be 0.1 (that would be 1%) - but instead 0.025 (0.25% - for math simplicity).
This is way below lotsize (which is what should be used for amounts) - effectively leaving me with 9.975 XXX. 
Effectively, since i can only sell in lots of 0.1, i will end up with 0.75 "binance dust" once this trade closes.



Now let's look at the binance result regarding precision:
```
{'percentage': True,
  'tierBased': False,
  'taker': 0.001,
  'maker': 0.001,
  'precision': {'base': 8, 'quote': 8, 'amount': 3, 'price': 6},
  'limits': {'amount': {'min': 0.001, 'max': 100000.0},
   'price': {'min': 1e-06, 'max': 100000.0},
   'cost': {'min': 0.0001, 'max': None}},
  'id': 'ETHBTC',
  'symbol': 'ETH/BTC',
  'base': 'ETH',
  'quote': 'BTC',
  'baseId': 'ETH',
  'quoteId': 'BTC',
  'info': {'symbol': 'ETHBTC',
   'status': 'TRADING',
   'baseAsset': 'ETH',
   'baseAssetPrecision': 8,
   'quoteAsset': 'BTC',
   'quotePrecision': 8,
}
   ...
}
```

precision is 8 for both base and quote. However, since we're having this problem with amount, we would need to use `amount` to be correct (no point in rounding amount to a price precision) - which has a precision of 3 - which i think is quite low for this type of comparison (with 3 - 0.0054 and 0.0055 would be identical).


``` python
math.isclose(0.0054, 0.0055, abs_tol=0.001)                                                                                   
True
```

Also keep in mind that these are "tradeable precisions" - not the precision binance will round to internally:

While ETH has a amount precision of 3 - you can still own it to a WAY lower percentage even though you can't trade it - which results in Binance dust (i have a lot of that in various currencies ...).

We do account for this on sell - using it to compare if a trade was filled completely or not may be dangerous, since (due to the above fee oddity) we can have bought an amount with more decimals than what are "tradeable".

**Comment by hroff-1902** [comment]
Ah, it's amount, not price, with it's own precision on the exchange...

Okay, why not `abs_tol=1e-14`?

**Comment by xmatthias** [comment]
because it is really a constant value we're using here - so `constants.py` seems a good place for it... 

and assuming we find this problem in other locations of the code, i would not want to have this a few times (or a few times slightly different)...

**Comment by hroff-1902** [comment]
erhm, I mean why it's rel_tol and not abs_tol?
(Just want to understand the details of the decision made)

**Comment by xmatthias** [comment]
to be honest, it's the first parameter (of the 2) in the argument list, worked for all cases i tested, and based on short circuiting, will be evaluated first (look at the last line of the C code linked above).

I assume abs_tol would work, too - but did not test it (and honestly, i don't read every PEP before using a function it introduces ...)

**Comment by xmatthias** [comment]
Don't put my decisions into question please... that'll have me start do the same ... :smile: 

rethinking this and testing it further i think you're right, `abs_tol` might be the safer way to go.

```python
In [2]: math.isclose(0.0054, 0.0055, abs_tol=1e-3)                                                                                     
Out[2]: True

In [3]: math.isclose(0.0054, 0.0055, rel_tol=1e-3)                                                                                     
Out[3]: False
```

on the other hand:
```
In [3]: math.isclose(20.0054, 20.0055, abs_tol=1e-3)                                                                                  
Out[3]: True

In [4]: math.isclose(20.0054, 20.0055, rel_tol=1e-3)                                                                                  
Out[4]: True

```

**Comment by hroff-1902** [comment]
That's what I was also thinking about... 

LGTM 👍

**Pull request merged**
