### PR TITLE
Backtest ticker interval unset

### PR DESCRIPTION
**Pull request by xmatthias**
## Summary
ticker-interval needs to be set for backtesting to work.
In case of strategy-list, it needs to be defined on either config or cli level, since each strategy could define it's own interval.

Solves #2099

## Quick changelog

- Fix uncought error
- add test for this behaviour

### CODE REVIEW

**Comment by xmatthias** [comment]
it doesn't really make a difference, since the only position this can be moved to is one line before `set_strategy` is called, since the strategy-loader can (in case of a single strategy) set the ticker_interval.

To be honest, i didn't spend much thought on moving it out of `set_strategy()` ... i moved the check to where we first use this - it's 2 executable lines between now and where we could move it to ...

**Comment by hroff-1902** [comment]
> it doesn't really make a difference, since the only position this can be moved to is one line before `set_strategy` is called, since the strategy-loader can (in case of a single strategy) set the ticker_interval.
> 
> To be honest, i didn't spend much thought on moving it out of `set_strategy()` ... i moved the check to where we first use this - it's 2 executable lines between now and where we could move it to ...

First of all, I appreciate you fixing that issue I filed (#2099 ).
Currently yes, it's just 2 lines above, but in the refactoring I mentioned, set_strategy will remain in Backtesting while most of current init will go to BacktestingCli. No problem with moving this check, but tests will also require to be adjusted in this case... And I thought I'm still not as familiar with pytest to make some sophisticated changes in tests effectively...

Okay, I'll make necessary changes during that my refactoring, let's merge it, thanks!

> 
> **edit**: there is even another enhancement in this structure - if ALL strategies define the same ticker-interval we COULD use that ... but i suspect most people will have ticker_interval in the configuration anyway.

I also thought of this, but will not the resulting behavior be too complex to describe it for the users in the docs?

**Comment by xmatthias** [comment]
> Currently yes, it's just 2 lines above, but in the refactoring I mentioned, set_strategy will remain in Backtesting while most of current init will go to BacktestingCli 

huh? i must have missed that ... ? where can i find this mention since now i'm curious ...

> I also thought of this, but will not the resulting behavior be too complex to describe it for the users in the docs?

Yes - that's why it's not there

**Comment by hroff-1902** [comment]
> > Currently yes, it's just 2 lines above, but in the refactoring I mentioned, set_strategy will remain in Backtesting while most of current init will go to BacktestingCli
> 
> huh? i must have missed that ... ? where can i find this mention since now i'm curious ...

Ah, oops, I experience some problems with github degradation, quite often in the last month it fails saving the comments. Seems I wrote it in a longer version of one of my previous comments which failed to go to github and also was not saved in the browser... Well, I'm splitting (splitted, not commited yet) backtesting for cli and non-cli parts and was stopped with #2099 ...

**Comment by hroff-1902** [comment]
Ah, no, I definitely mentioned this here above:

> Thanks for fixing it. I was refactoring backtesting -- splitting it to cli and non-cli parts and stopped with this issue...

Nevermind...

**Comment by xmatthias** [comment]
> Well, I'm splitting (splitted, not commited yet) backtesting for cli and non-cli parts

i'm not sure about the reason for this - i guess it's to align to edge, but the reason for that is that edge used within the bot itself (during real operations) - while backtesting is not - so honestly, i think it's effort not well spent (i think we should discuss bigger refactorings (like this) in a dedicated issue before spending time on it.

**Pull request merged**
