### PR TITLE
Increase code coverage and improve Pylint

### PR DESCRIPTION
**Pull request by glonlas**
## Summary
We cannot stay at only 96% of code coverage and be having a Pylint score going down.
This PR is to cover part of the code not tested but unit tests and cleaning code by improving Pylint score.

### CODE REVIEW

**Comment by vertti** [comment]
@glonlas what's up with this? Should we just get this in and continue in next PR's.

**Comment by glonlas** [comment]
If tests pass, we can merge it

**Comment by xmatthias** [comment]
if it's only mypy in test-files - i think we should consider `#type: ignore` for these lines ... 

typechecking fine and well - but it may not be worth the effort for tests ...

**Comment by vertti** [comment]
I'd consider disabling mypy for all test files.

**Comment by xmatthias** [comment]
took the liberty to add the mypy test exclusion to this branch.

**Pull request merged**
