### PR TITLE
Allow multi strategy backtest without data reload

### PR DESCRIPTION
**Pull request by xmatthias**
## Summary
This PR will allow backtesting multiple strategies at once efficiently, as startup/spindown time of backtest makes most of the time (loading data, ...).

## Quick changelog

- introduce new command line option `--strategy-list`

## Changes

* [x] Add command line option
* [x] Prove it works
* [x] documentation
* [x] export trades with strategy name inside
* [x] improve readability of backtest report (happy to hear ideas)
* [x] use print for output (allows using `freqtrade backtesting --strategy-list > filename` to gather results / look at them in an editor)

## New output

the backtesting output is printed once per strategy (with the strategy-name)
The strategy-comparison table is only printed if more than 1 strategy is selected.

the full output of 2 strategies backtested would look as follows:

```
2018-07-29 13:07:53,724 - freqtrade.optimize.backtesting - INFO - 
Result for strategy BinHV27
2018-07-29 13:07:53,750 - freqtrade.optimize.backtesting - INFO - 
================================================== BACKTESTING REPORT =================================================
| pair      |   buy count |   avg profit % |   cum profit % |   total profit ETH | avg duration     |   profit |   loss |
|:----------|------------:|---------------:|---------------:|-------------------:|:-----------------|---------:|-------:|
| LTC/ETH   |           1 |          -5.04 |          -5.04 |        -0.00504817 | 2 days, 7:05:00  |        0 |      1 |
| IOTA/ETH  |           0 |         nan    |           0.00 |         0.00000000 | 0:00             |        0 |      0 |
| XMR/ETH   |           4 |          -0.10 |          -0.42 |        -0.00041939 | 6:01:00          |        3 |      1 |
| XRP/ETH   |           3 |           0.29 |           0.86 |         0.00086551 | 5:22:00          |        3 |      0 |
| NCASH/ETH |           2 |          -2.13 |          -4.26 |        -0.00426041 | 15:48:00         |        1 |      1 |
| MTH/ETH   |           1 |         -14.99 |         -14.99 |        -0.01500944 | 5 days, 11:10:00 |        0 |      1 |
| AST/ETH   |           5 |           1.31 |           6.57 |         0.00657878 | 4:04:00          |        5 |      0 |
| TNT/ETH   |           2 |           1.25 |           2.50 |         0.00249883 | 3:15:00          |        2 |      0 |
| ETC/ETH   |           1 |           0.39 |           0.39 |         0.00039142 | 15:15:00         |        1 |      0 |
| TOTAL     |          19 |          -0.76 |         -14.39 |        -0.01440287 | 15:48:00         |       15 |      4 |
2018-07-29 13:07:53,751 - freqtrade.optimize.backtesting - INFO - 
================================================== SELL REASON STATS ==================================================
| Sell Reason   |   Count |
|:--------------|--------:|
| sell_signal   |      15 |
| force_sell    |       4 | 

2018-07-29 13:07:53,778 - freqtrade.optimize.backtesting - INFO - 
=============================================== LEFT OPEN TRADES REPORT ===============================================
| pair      |   buy count |   avg profit % |   cum profit % |   total profit ETH | avg duration     |   profit |   loss |
|:----------|------------:|---------------:|---------------:|-------------------:|:-----------------|---------:|-------:|
| LTC/ETH   |           1 |          -5.04 |          -5.04 |        -0.00504817 | 2 days, 7:05:00  |        0 |      1 |
| IOTA/ETH  |           0 |         nan    |           0.00 |         0.00000000 | 0:00             |        0 |      0 |
| XMR/ETH   |           1 |          -0.67 |          -0.67 |        -0.00066669 | 7:45:00          |        0 |      1 |
| XRP/ETH   |           0 |         nan    |           0.00 |         0.00000000 | 0:00             |        0 |      0 |
| NCASH/ETH |           1 |          -5.01 |          -5.01 |        -0.00501031 | 1 day, 6:45:00   |        0 |      1 |
| MTH/ETH   |           1 |         -14.99 |         -14.99 |        -0.01500944 | 5 days, 11:10:00 |        0 |      1 |
| AST/ETH   |           0 |         nan    |           0.00 |         0.00000000 | 0:00             |        0 |      0 |
| TNT/ETH   |           0 |         nan    |           0.00 |         0.00000000 | 0:00             |        0 |      0 |
| ETC/ETH   |           0 |         nan    |           0.00 |         0.00000000 | 0:00             |        0 |      0 |
| TOTAL     |           4 |          -6.43 |         -25.71 |        -0.02573461 | 2 days, 8:11:00  |        0 |      4 |
2018-07-29 13:07:53,779 - freqtrade.optimize.backtesting - INFO - Dumping backtest results to user_data/backtest_data/backtest-result-BinHV45.json
dumping json to "user_data/backtest_data/backtest-result-BinHV45.json"
2018-07-29 13:07:53,780 - freqtrade.optimize.backtesting - INFO - 
Result for strategy BinHV45
2018-07-29 13:07:53,806 - freqtrade.optimize.backtesting - INFO - 
================================================== BACKTESTING REPORT =================================================
| pair      |   buy count |   avg profit % |   cum profit % |   total profit ETH | avg duration     |   profit |   loss |
|:----------|------------:|---------------:|---------------:|-------------------:|:-----------------|---------:|-------:|
| LTC/ETH   |           0 |         nan    |           0.00 |         0.00000000 | 0:00             |        0 |      0 |
| IOTA/ETH  |           0 |         nan    |           0.00 |         0.00000000 | 0:00             |        0 |      0 |
| XMR/ETH   |           0 |         nan    |           0.00 |         0.00000000 | 0:00             |        0 |      0 |
| XRP/ETH   |           0 |         nan    |           0.00 |         0.00000000 | 0:00             |        0 |      0 |
| NCASH/ETH |           1 |           1.31 |           1.31 |         0.00130853 | 1:40:00          |        1 |      0 |
| MTH/ETH   |           1 |         -10.33 |         -10.33 |        -0.01034067 | 2 days, 11:55:00 |        0 |      1 |
| AST/ETH   |           1 |           2.19 |           2.19 |         0.00218995 | 5:25:00          |        1 |      0 |
| TNT/ETH   |           3 |          -3.19 |          -9.56 |        -0.00957080 | 2 days, 6:05:00  |        1 |      2 |
| ETC/ETH   |           0 |         nan    |           0.00 |         0.00000000 | 0:00             |        0 |      0 |
| TOTAL     |           6 |          -2.73 |         -16.40 |        -0.01641299 | 1 day, 14:12:00  |        3 |      3 |
2018-07-29 13:07:53,807 - freqtrade.optimize.backtesting - INFO - 
================================================== SELL REASON STATS ==================================================
| Sell Reason   |   Count |
|:--------------|--------:|
| roi           |       3 |
| stop_loss     |       2 |
| force_sell    |       1 | 

2018-07-29 13:07:53,833 - freqtrade.optimize.backtesting - INFO - 
=============================================== LEFT OPEN TRADES REPORT ===============================================
| pair      |   buy count |   avg profit % |   cum profit % |   total profit ETH | avg duration   |   profit |   loss |
|:----------|------------:|---------------:|---------------:|-------------------:|:---------------|---------:|-------:|
| LTC/ETH   |           0 |         nan    |           0.00 |         0.00000000 | 0:00           |        0 |      0 |
| IOTA/ETH  |           0 |         nan    |           0.00 |         0.00000000 | 0:00           |        0 |      0 |
| XMR/ETH   |           0 |         nan    |           0.00 |         0.00000000 | 0:00           |        0 |      0 |
| XRP/ETH   |           0 |         nan    |           0.00 |         0.00000000 | 0:00           |        0 |      0 |
| NCASH/ETH |           0 |         nan    |           0.00 |         0.00000000 | 0:00           |        0 |      0 |
| MTH/ETH   |           0 |         nan    |           0.00 |         0.00000000 | 0:00           |        0 |      0 |
| AST/ETH   |           0 |         nan    |           0.00 |         0.00000000 | 0:00           |        0 |      0 |
| TNT/ETH   |           1 |          -0.79 |          -0.79 |        -0.00079319 | 16:30:00       |        0 |      1 |
| ETC/ETH   |           0 |         nan    |           0.00 |         0.00000000 | 0:00           |        0 |      0 |
| TOTAL     |           1 |          -0.79 |          -0.79 |        -0.00079319 | 16:30:00       |        0 |      1 |
2018-07-29 13:07:53,838 - freqtrade.optimize.backtesting - INFO - 
=================================================== Strategy Summary===================================================
| Strategy   |   buy count |   avg profit % |   cum profit % |   total profit ETH | avg duration    |   profit |   loss |
|:-----------|------------:|---------------:|---------------:|-------------------:|:----------------|---------:|-------:|
| BinHV27    |          19 |          -0.76 |         -14.39 |        -0.01440287 | 15:48:00        |       15 |      4 |
| BinHV45    |           6 |          -2.73 |         -16.40 |        -0.01641299 | 1 day, 14:12:00 |        3 |      3 |

```

### CODE REVIEW

**Comment by berlinguyinca** [comment]
can we add a feature to fetch the strategies to test from the freqshow rest service? Or make it an optional argument, so I can easily embed it into other code

**Comment by xmatthias** [comment]
not with this PR ... it currently requires all strategies to be in the same folder (that's the documentation-part which is missing)

but to fetch strategies should be as simple as a bash script downloading it all into the folder and then running ... should be a 3liner or so

**Comment by berlinguyinca** [comment]
true, just wanted to be lazy

**Comment by berlinguyinca** [comment]
eta for merge? Kinda want to get this into freqshow, so it can be live again instead of being dead right now, due to lack of data

**Comment by xmatthias** [comment]
Rebased onto develop to fix conflicts.
Can't tell you that - i cannot review my own PR - i'm very biased, sorry.

**Pull request merged**
