### PR TITLE
add buy_tag to trade tooltip in plots

### PR DESCRIPTION
**Pull request by italodamato**
## Summary

add buy_tag to trade tooltip in plots, it makes it easier to troubleshoot strategies

## Quick changelog

- added the trade `buy_tag` to the tooltip shown in plots

### CODE REVIEW

**Comment by xmatthias** [comment]
I'd recommend running the "common" tools we have locally first [documented here](https://github.com/freqtrade/freqtrade/blob/develop/CONTRIBUTING.md#before-sending-the-pr).

Passing tests/CI is one core requirement ... and it's usually pretty simple (and a lot faster locally, where you don't have to wait for 15 minutes for CI to tell you what's wrong).

**Review by xmatthias — COMMENTED** [review]
am i correct in assuming that the only change to the json file is the addition of one "buy_tag" field? (it's difficult to compare that file as it's all in one line ...).

**Comment by italodamato** [comment]
> am i correct in assuming that the only change to the json file is the addition of one "buy_tag" field? (it's difficult to compare that file as it's all in one line ...).

Yes just added `buy_tag` on the second trade

**Review by xmatthias — APPROVED** [review]
LGTM :+1: 

Nice enhancement, thanks a ton! :100:

**Pull request merged**
