### PR TITLE
Fix #1840 - Support balances other than USDT

### LINKED ISSUE #1840: Permanent "all balances are zero" on kraken
## Step 1: Have you search for this issue before posting it?
Yes !

## Step 2: Describe your environment

  * Python Version: 3.6.7 (`python -V`)
  * CCXT version: 1.18.516 (`pip freeze | grep ccxt`)
  * Branch: Develop
  * Last Commit ID: 867f9ae362354be7ecd70f73b9570a2f4c124a9e (`git log --format="%H" -n 1`)
  
### Observed Results:

The bot runs on kraken -> starts well.
Dry mode is disabled.
On Telegram, if I ask for /balance, I obtain  'All balances are at zero' whereas my kraken account has some euros.

### Relevant code exceptions or logs:
In the command line, I obtain the following output.
(Warning: the configured pair is BTC/EUR, with EUR as stake_currency, not EUR/BTC ! -> I do not know why it makes the invertion)
  ```
2019-05-11 12:38:22,308 - freqtrade.rpc.telegram - INFO - Executing handler: _balance for chat_id: XXXXXXXXXX
2019-05-11 12:38:22,636 - freqtrade.exchange.exchange - WARNING - get_ticker() returned exception: "Pair EUR/BTC not available"
2019-05-11 12:38:22,636 - freqtrade.exchange.exchange - WARNING - retrying get_ticker() still for 3 times
2019-05-11 12:38:22,637 - freqtrade.exchange.exchange - WARNING - get_ticker() returned exception: "Pair EUR/BTC not available"
2019-05-11 12:38:22,637 - freqtrade.exchange.exchange - WARNING - retrying get_ticker() still for 2 times
2019-05-11 12:38:22,638 - freqtrade.exchange.exchange - WARNING - get_ticker() returned exception: "Pair EUR/BTC not available"
2019-05-11 12:38:22,638 - freqtrade.exchange.exchange - WARNING - retrying get_ticker() still for 1 times
2019-05-11 12:38:22,639 - freqtrade.exchange.exchange - WARNING - get_ticker() returned exception: "Pair EUR/BTC not available"
2019-05-11 12:38:22,639 - freqtrade.exchange.exchange - WARNING - retrying get_ticker() still for 0 times
2019-05-11 12:38:22,639 - freqtrade.exchange.exchange - WARNING - get_ticker() returned exception: "Pair EUR/BTC not available"
2019-05-11 12:38:22,639 - freqtrade.exchange.exchange - WARNING - Giving up retrying: get_ticker()

  ```

Please note that kraken previously made you trade bitcoin with the XBT symbol.
It now makes you trade with BTC symbol.

I tried to fallback on XBT/EUR pair and it output this:
  ```
2019-05-11 12:43:06,855 - freqtrade - ERROR - Pair XBT/EUR is not available on Kraken. Please remove XBT/EUR from your whitelist.

  ```

### PR DESCRIPTION
**Pull request by xmatthias**
## Summary
Getting the balance for some currencies (EUR / USD) needs to invert the pair.

Fixes: #1840

## Quick changelog

- Add EUR and USD to the inverted pairs

### CODE REVIEW

**Comment by hroff-1902** [comment]
I'm not against the changes made, just a question: in principle, this should be exchange specific (specific for Kraken), right?

**Comment by xmatthias** [comment]
yes and no - currently for kraken, but binance wants to support FIAT currencies in the near future (that's one of the terms they are legally in malta now, as far as i know), so it'll be for binance too, and probably for all/most other exchanges trading FIAT currencies.

In theory, we could try the pair one side, and then the other (if it doesn't work one way) ... but since the list of pairs this affects is very limited i'm not sure on the benefit.

**Comment by hroff-1902** [comment]
But why do you assume that fiat pairs at binance will be reverse as well, as on kraken, for which this patch is correct?
Remember, one of the users at Slack said he was able to run freqtrade successfully at 7 exchanges. He did not tell the complete list of the exchanges, but... Do they all contain those pairs as reverse pairs, if any? I mean, don't you think that such a wide patch may simply break compatibility with some of the exchanges that the bot was able to work before?...

**Comment by xmatthias** [comment]
Having the bot working - and `/balance` report all currencies are 2 different things. 
Notice that this will ONLY impact `/balance` - it's not a general handling of this pair.

**Comment by hroff-1902** [comment]
Okay, and kraken definitely is not in the list of 'officially' supported exchanges (as the rest of the exchanges), but I would only tell that fetching all those exchange-specific parts from the codebase could be non-trivial task in the future...

**Comment by sgarcia159** [comment]
I believe I might be experiencing a similar issue. I am trying to use Kraken. I wanted to trade in EUR however I kept receiving the following error:
WARNING - Unable to create trade: Available balance(0 EUR) is lower than stake amount(19 EUR). I have more than enough EUR to cover 19 EUR.  after  few days Googling without success. I decided to at least trade a little BTC. Now I am receving the below error for BTC transactions. I've attached logfiles from both attempts

Thanks in advance.


[KrakenE.txt](https://github.com/freqtrade/freqtrade/files/3572248/KrakenE.txt)
[UpdatedRPC_BTC.txt](https://github.com/freqtrade/freqtrade/files/3572249/UpdatedRPC_BTC.txt)
Traceback (most recent call last):
  File "/home/sgarc90/freqtrade/freqtrade/rpc/telegram.py", line 52, in wrapper
    return command_handler(self, *args, **kwargs)
  File "/home/sgarc90/freqtrade/freqtrade/rpc/telegram.py", line 336, in _balance
    "\t`Est. BTC: {est_btc: .8f}`\n".format(**currency)

**Comment by xmatthias** [comment]
@sgarcia159 please open a new issue for this. Highjacking old Pull requests is the best way to have people overlook your messages. 

The logs are non-conclusive in this case, but i would suggest to verify that the exchange keys are correct as well.

**Comment by sgarcia159** [comment]
Thanks for your email. I'm new at this. I'll create a post soon as I can.

Sam

**Pull request merged**
