### PR TITLE
Refactor config

### PR DESCRIPTION
**Pull request by xmatthias**
## Summary
Simplify configuration class complexity by extracting repeated logic of "check if key is in namespace", "copy it to config", "print log" to a separate function.

## Quick changelog

- simplify configuration class
- combine all optimize logics (they are all called anyway, so it does not matter where it applies).
- removed duplicate entries (--timerange, --refresh_pairs, ...) since all where always called anyway.

### CODE REVIEW

**Comment by hroff-1902** [comment]
LGTM,
let this be in this manner.

I'll probably refactor this a bit futher, some time later... Let this be as it is for now... (I mean the _args_to_config() function. It can later be simplified and improved, I guess...)

Also, you moved processing of all optimization parameters to the single function. I also wanted to move *common* optimization params to _load_optimize_config(), *but* I supposed to leave processing of the edge, backtesting and hyperopt-specific params in the corresponding functions... Can be done later, let's merge it to have the new fixed starting point for further improvements...

**Comment by xmatthias** [comment]
Honestly, everything may be further refactored ... code of a living project is rarely at a standstill

one idea i had was to immediately covert args to a dict on initialization of the config class, which will allow to use `args.get('param', default)` ... but one step at a time.

the dubious concerns me however - you think there is a bug or problem in the code?

**Comment by hroff-1902** [comment]
> the dubious concerns me however - you think there is a bug or problem in the code?

Nope, I guess my doubts are, 1st, related to the names of the command line parameters in the logstrings (like 'Parameter --enable-position-stacking detected ...'). All them should ideally be located in the arguments.py, that's why they create doubts. But current implementaion also contain them in configuration.py... Second -- a funcky (looking a bit strange, but I understand why you have added it) logfun argument,,, Third -- I personally liked two diff log messages for 'Detected...' and 'Using...' Fourth: absense of separate functions for processing edge, backtesting and hyperopt params -- they can easily be added.

So let's merge it and I'll think later on how to move those names of the command line params to arguments.py. Maybe other stuff get simplier then...

**Comment by xmatthias** [comment]
> absense of separate functions for processing edge, backtesting and hyperopt params

most of them are combined - and parsing / setting an option that is not used should not cause trouble (i would hope)...

**Pull request merged**
