### PR TITLE
split up test_freqtradebot.py

### PR DESCRIPTION
**Pull request by xmatthias**
## Summary
Split up `test_freqtradebot.py` into `test_worker.py` and `test_integration.py` to be clearer what is tested.

test_integration shall grow in the future, adding test-cases which try to mimic the full cycle of trades or trading scenarios.

## Quick changelog

- Add test_worker.py
- add test_integration.py
- add test trying to reproduce #1985 (seems ok in test - needs more info from reporter... )

### CODE REVIEW

**Comment by hroff-1902** [comment]
> Add test_worker.py 

-- did not we have it before? 🙄

**Comment by xmatthias** [comment]
no we decided to keep tests for worker in `test_freqtrade.py` at the time ...

**Comment by hroff-1902** [comment]
why do you call it 'integration'?

**Comment by xmatthias** [comment]
> why do you call it 'integration'?

because i suck at naming things ... give me a better suited name and i'll jump on it without thinking twice...

it's kinda integration tests - as they don't unittests specific functions, but the interaction between different elements within freqtradebot.py.

to quote [wikipedia](https://en.wikipedia.org/wiki/Integration_testing):

> Integration testing [...] is the phase in software testing in which individual software modules are combined and tested as a group.

It's probably not real integration tests (i assume these should not mock anything ...?) ... but these come at least close (i hope).

**Comment by hroff-1902** [comment]
Then in this case it's okay (it could probably also named `test_freqtradebot_integration.py`, but current name is okay), thanks for explanation.

**Pull request merged**
