### PR TITLE
Trailing stop loss

### PR DESCRIPTION
**Pull request by chrisapril**
This PR is adding a Trailing Stop Loss functionality.

### CODE REVIEW

**Comment by glonlas** [comment]
Hello @chrisapril,

Is it possible to have a description of the problem this PR solve, how it solve it and what is the behavior to expect? It will help to understand how it should works.

If you look on how to test your code and check if your are PEP8 compliant, I have written a short wiki page about it here: https://github.com/glonlas/freqtrade/wiki/How-to-check-if-your-PR-is-good-to-send%3F

**Comment by Alam11** [comment]
I tried to implement the same functionality some time ago. Can I ask you a few questions ? In main.py line 174 you check if current_profit > 0. Name of this function suggest that you want to stop losses, and there are no losses if the profit is positive. This code acts like trailing ROI or better yet, trailing window, based on max function, with fixed width. Is that correct ? Second question is why is there stat_min_rate field not used anywhere ? Also, you seem to keep  trade.stat_max_rate as absolute value. If i might suggest different approach - I keep it as % of loss/gain as stop loss is. That would simplify the code in main.py line  179.

**Comment by pan-long** [comment]
This PR hasn't been updated for 2 mouths @chrisapril what's the status? Are you still working on this PR?

**Comment by xmatthias** [comment]
closing this in favor of #963 since there has been no activity in the last 6 months.

**Pull request closed without merging**
