### PR TITLE
Added Telegram command "logs [n]"

### PR DESCRIPTION
**Pull request by pnmartinez**
## Summary
Telegram command to check last [n] entries of the logs.

## Quick changelog

- freqtrade/freqtrade/rpc/telegram.py
    - `import os` added to access the logs on the filesystem,
    - Added _logs function, 
    - command handler, 
    - and command explanation on the "/help" message.

## What's new?
Checking the current status of the bot can be useful while being afk. This command enables to check the logfile from the Telegram bot; the text formatting may be not smartphone friendly, but it helped me in more than one occasion.

Posting in case it is useful for anyone else.

### CODE REVIEW

**Comment by hroff-1902** [comment]
it will not work if the path to the logfile was altered with the `--logfile` option, this should be handled..

**Comment by xmatthias** [comment]
it will not work by default, as logs are not written to disk unless explicitly specified...

I would like such a functionality myself - but i don't think relying on re-reading a log-file is a good aproach. 
Worst case is that it'll lock the bot due to concurrency ...

**Comment by hroff-1902** [comment]
there is a queue-based logging available in the python world,
we could add the handler for it, keeping some amount (100, 1000) last logging messages in the queue, which can be requested and sent to the rpc client.
queueing the logs will also resolve the problem with first log messages (that are issued before the configuration is read and the log settings handled) that are now not displayed...

**Comment by xmatthias** [comment]
> there is a queue-based logging available in the python world,
> we could add the handler for it, keeping some amount (100, 1000) last logging messages in the queue, which can be requested and sent to the rpc client.
> queueing the logs will also resolve the problem with first log messages (that are issued before the configuration is read and the log settings handled) that are now not displayed...

now this (queueing) is in my list of stashes ... but not fully tested nor completely implemented ...

**Comment by xmatthias** [comment]
Thanks for your interrest and contribution.

However, for the above reasons (logging to file not default, reading from file may lead to locking, reading from file is bad practice, and may give different results depending if the log has been recently rotated or not) - this method implementing this is not the right way.

We're more than happy to provide / accept such a feature - but it should not re-read the log-file - but instead query logging module internally, which - if done correctly, will provide this information.

**Comment by pnmartinez** [comment]
> Thanks for your interrest and contribution.
> 
> However, for the above reasons (logging to file not default, reading from file may lead to locking, reading from file is bad practice, and may give different results depending if the log has been recently rotated or not) - this method implementing this is not the right way.
> 
> We're more than happy to provide / accept such a feature - but it should not re-read the log-file - but instead query logging module internally, which - if done correctly, will provide this information.

No problem! Hoping that the quick fix that made for me would open the conversation about this. Thanks for the feedback.

**Pull request closed without merging**
