### PR TITLE
Trades table update

### PR DESCRIPTION
**Pull request by creslinux**
with re to issue #1053 

This change is to update the trades table after sale. 
Currently the trades table is updated on the next loop around all the pairs. This many be many minutes if the users has 60-120 pairs loaded. 

The aligns trades table view of the world with exchange and RPC  push messages.

### CODE REVIEW

**Comment by xmatthias** [comment]
Please do a clean checkout of the development branch and make your commit on top of this ...
with this history (143 commits for 1 line changed) this cannot be merged, sorry.

**Comment by xmatthias** [comment]
apart from the git history - this creates a recursive loop...

* `process_maybe_execute_sell` calls `handle_trade`
* `handle_trade` calls `execute_sell`
* `execute_sell` now calls `process_maybe_execute_sell` again ...

**Comment by creslinux** [comment]
loops and git issues - pulled!

**Comment by creslinux** [comment]
Having looked on this, I don't think it is a loop as  
` trade.open_order_id = order_id `

is set before calling, so we would never hit the handle_trade logic. 

Struggling with GIT. Moving develop to develop_bak left pycharm in a very broken state.

**Pull request closed without merging**
