### PR TITLE
fix #2008

### LINKED ISSUE #2008: Strong deviations between Hyperopt and Backtest Results
## Step 1: Have you search for this issue before posting it?

If you have discovered a bug in the bot, please [search our issue tracker](https://github.com/freqtrade/freqtrade/issues?q=is%3Aissue). 
If it hasn't been reported, please create a new issue.

## Step 2: Describe your environment

  * Python Version: 3.7.3
  * CCXT version: pip freeze | grep ccxt
  * Branch: Develop
  * Last Commit ID: d055dc0c6e0aa24297e5309eee7ea7e511bf9e51

  
## Step 3: Describe the problem:

Strong deviations between Hyperopt and Backtest Results, **number of trades and total profit**

### Steps to reproduce:

  1. strategy (MACD and CCI based) coded in Hyperopt to find the best parameters for the CCI buy / sell, stoploss and ROIs
  2. run Hyperopt
  3. put the paramters in the strategy and backtested over the same timeframe as hyperopt was running
  
### Observed Results:

Results should be similar, correct?

### Relevant code exceptions or logs:

hyperopt results

  ```
2019-07-09 07:01:39,815 - freqtrade.exchange.exchange - INFO - downloaded LINK/BTC with length 1.
2019-07-09 07:01:39,816 - freqtrade.misc - INFO - dumping json to "user_data/data/binance/LINK_BTC-5m.json"
2019-07-09 07:01:40,851 - freqtrade.data.converter - INFO - Missing data fillup for LINK/BTC: before: 71711 - after: 71999
2019-07-09 07:01:40,884 - freqtrade.optimize.hyperopt - INFO - Hyperopting with data from 2018-11-01T05:05:00+00:00 up to 2019-07-09T04:55:00+00:00 (249 days)..

2019-07-09 09:43:45,460 - freqtrade.optimize.hyperopt - INFO - Best result:
   604 trades. Avg profit  0.53%. Total profit  0.48081498 BTC ( 320.22Σ%). Avg duration 1292.9 mins.
with values:

{   'buy-cci-value': -12,
    'roi_p1': 0.014714316102334512,
    'roi_p2': 0.06416378274370114,
    'roi_p3': 0.12198411469836923,
    'roi_t1': 114,
    'roi_t2': 43,
    'roi_t3': 33,
    'sell-cci-value': 158,
    'stoploss': -0.4700606834872094}


  ```

Backtest results

  ```

2019-07-09 16:59:11,178 - freqtrade.optimize.backtesting - INFO - Backtesting with data from 2018-11-01T00:00:00+00:00 up to 2019-07-08T23:55:00+00:00 (249 days)..
2019-07-09 16:59:11,178 - freqtrade.optimize.backtesting - INFO - Running backtesting for Strategy MACDStrategy1
Result for strategy MACDStrategy1
========================================================= BACKTESTING REPORT ========================================================
| pair     |   buy count |   avg profit % |   cum profit % |   tot profit BTC |   tot profit % | avg duration    |   profit |   loss |
|:---------|------------:|---------------:|---------------:|-----------------:|---------------:|:----------------|---------:|-------:|
| LINK/BTC |          88 |           0.63 |          55.61 |       0.08349766 |          18.54 | 2 days, 6:31:00 |       33 |      1 |
| TOTAL    |          88 |           0.63 |          55.61 |       0.08349766 |          18.54 | 2 days, 6:31:00 |       33 |      1 |
========================================================= SELL REASON STATS =========================================================
| Sell Reason   |   Count |
|:--------------|--------:|
| roi           |      87 |
| force_sell    |       1 |
====================================================== LEFT OPEN TRADES REPORT ======================================================
| pair     |   buy count |   avg profit % |   cum profit % |   tot profit BTC |   tot profit % | avg duration   |   profit |   loss |
|:---------|------------:|---------------:|---------------:|-----------------:|---------------:|:---------------|---------:|-------:|
| LINK/BTC |           1 |          -5.67 |          -5.67 |      -0.00851834 |          -1.89 | 11:40:00       |        0 |      1 |
| TOTAL    |           1 |          -5.67 |          -5.67 |      -0.00851834 |          -1.89 | 11:40:00       |        0 |      1 |


  ```

### PR DESCRIPTION
**Pull request by hroff-1902**
Resolves #2008 

(A helping debug message was also added, but commented out since it contains long dataframe and is noisy therefore...)

This probably closes a couple of old issues as well (related to the deviations found between hyperopt and backtesting results), pls check.

### CODE REVIEW

**Comment by hroff-1902** [comment]
Besides #2008, here come yet another reasons: if eps is True for hyperopt, there should be the --dps command line option for hyperopt to disable it from the command line. Plus, the --eps option should not be common for all optimization subcommands. Plus, the description of the --eps option should probably differ for backtesting and hyperopts if it still common option, reflecting diff. default values for the subcommand.

And the main argument is that I did not find in the issues any reasons why this 'unrealistic' mode should be default.

I named the eps=False mode realistic by myself first and only then found in the issues that it was an option previously with that name. So it's really realistic/unrealistic... Unrealistic results only do raise questions from the users and falsy expectations from their strategies that are under hyperopting...

**Comment by xmatthias** [comment]
The reason for hyperopt were performance reasons - no need to look that up - i experienced that myself when this command was split.

we've done a lot to hyperopt since, so maybe they're gone - but i think that'll need extensive testing first.

**Comment by hroff-1902** [comment]
btw, `--dmmp` is now has no effect for hyperopt (the value is not passed in the dict of args to `backtest()` so the default value of 0 is always used). Is it a bug or it does works as intended?

**Comment by xmatthias** [comment]
err ... i guess behaviour should be similar to backtesting if we have that parameter ... ? 

but to be honest, it's been a long time since i "really" used hyperopt for more than testing (no time :( )

**Comment by hroff-1902** [comment]
I adjusted the docs, pls review the style and the wordings, add some more descriptive points if you have something to add...

I guess the 'Position stacking and disabling max market positions.' section should also be copied somewhere into backtesting.md...

Ready for merge?

**Pull request merged**
