### PR TITLE
Backtest data validation

### PR DESCRIPTION
**Pull request by xmatthias**
## Summary
Backtest data may not always be clean, missing values can taint backtest results.

## Quick changelog

- move get_timeframe out of the backtest class
- introduce `optimize.validate_backtest_data` (which prints a warning if data is missing)
- add script to plot details of the missing data (the missing data)

## What's new?
Script output:
```
python scripts/validate_backtest_data.py -p TRX/ETH,TRIG/ETH -i 5m -d user_data/data/binance/
2018-10-18 20:24:49,405 - __main__ - INFO - Starting Validate backtest data
2018-10-18 20:24:50,172 - freqtrade.optimize - WARNING - TRX/ETH has missing frames: expected 57815, got 57584, that's 231 missing values
2018-10-18 20:24:50,172 - freqtrade.optimize - WARNING - TRIG/ETH has missing frames: expected 57815, got 57584, that's 231 missing values
2018-10-18 20:24:50,239 - __main__ - INFO - Found dirty data for pair TRX/ETH
                           open  high  low  close  volume
date                                                     
2018-06-26 02:00:00+00:00   NaN   NaN  NaN    NaN     0.0
2018-06-26 02:05:00+00:00   NaN   NaN  NaN    NaN     0.0
2018-06-26 02:30:00+00:00   NaN   NaN  NaN    NaN     0.0
2018-06-26 03:30:00+00:00   NaN   NaN  NaN    NaN     0.0
...
```

### CODE REVIEW

**Comment by mishaker** [comment]
nooooooo !!! I was thinking of implementing it today :)))

**Comment by wingsgb** [comment]
I agree with Mishaker that a error would be best in this situation to prevent further confusion in the end results.

**Comment by xmatthias** [comment]
raising the log-level to error will not automatically abort the backtest - so i'm not sure about the gain.

missing data is a valid scenario in live-runs too - we sometimes see the "outdated ticker" message - which i saw happening during periods of inactivity - interval spans with 0 (no) activity. Some exchanges show "no activity" in the corresponding field - but the API simply doesn't return a datapoint for this period (not sure that's correct from them - but that's another topic). This won't happen in high volume pairs (ETH/BTC | BTC/USDT | ...) - but on low-value coins with low volume (which you can still get good gains from with the right strategy)

based on the above paragraph - having backtest block operation could render backtesting on 1min data close to impossible on lower volume pairs as you might have some missing datapoints for most periods.

**Comment by xmatthias** [comment]
>When strategy sets both buy and sell signal on a signal candle (should it be considered a corrupt strategy so rejected?)

that means your strategy might have issues - yes - however selling if buy-signal is still available can be disabled in the `"experimental"` settings.

 i'm not sure i understand your 2nd point - but having this discussion in a PR is dangerous as once it's closed not many will look at this anymore.

**Pull request merged**
