### PR TITLE
Futures pairlist

### PR DESCRIPTION
**Pull request by xmatthias**
## Summary

Allow futures / margin pairs to be selected

## Quick changelog

Update output of `list-pairs` and `list-markets` to include futures/margin pairs.

For binance, the dedicated binance-futures (e.g. `binanceusdm`) has to be selected.

### CODE REVIEW

**Comment by rokups** [comment]
Relevant: https://github.com/freqtrade/freqtrade/blob/develop/freqtrade/strategy/informative_decorator.py#L88
I was thinking about this bit. It really should do this:
```py
# asset is one of: 'BTC-PERP`, 'BTC-1231', 'BTCUSDT`
base, quote = exchange.get_market(asset)['base_currency'], config['stake_currency']
```
`pair` is a really confusing name when it comes to futures. For example binance names futures like `BTCUSDT` while FTX names futures like `BTC-PERP`/`BTC-1231`. There is no guarantee for base currency being in the name, nor there is any guarantee where in the name it would appear. I did not look further into it, but this change seems like a perfect place taking care of decorator detail. Actually if we start looking data up in market info then `if '/' in asset:` becomes unnecessary.

**Comment by xmatthias** [comment]
@rokups this was my argument back when you added the automatic "pair detections" to the `@informative` part, too.
We didn't use `/` to split pairs anywhere else until then in the `@informative`.
Dataprovider has access to markets, too - so this should not be a problem in theory.

Now for this particular PR, I'd not like to touch informative pairs (like, not at all) - as this is to simply enable a very simple pairlist to work on a futures / margin configuration (no informative and whatnot). 
However, the fixes to @informative (and other places) will for sure also be necessary.

**Comment by rokups** [comment]
Alright then. Still we could talk about it. Reason for that dirty pair name parsing is simplicity. To do it properly we need access to markets, to access markets we need to poke exchange object. And it gets stupid there... Strategy class does not really have any need to access exchange, except for this detail. I do not see an elegant way to solve that 😞

**Comment by xmatthias** [comment]
Strategy gets access to markets through dataprovider, it has that access already now IIRC (at least in a limited form- but providing the full dict wouldn't be a problem either).

**Comment by rokups** [comment]
```
/home/rk/src/freqtrade/venv/lib/python3.9/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'ICX-PERP'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)
2021-11-07 18:08:01,957 - freqtrade.data.history.history_utils - INFO - Downloading pair ICX-PERP, interval 5m.
2021-11-07 18:08:01,957 - freqtrade.data.history.history_utils - INFO - Download history data for pair: "ICX-PERP" (54/54), timeframe: 5m and store in user_data_futures_ftx/data/ftx.
2021-11-07 18:08:20,092 - freqtrade.exchange.exchange - INFO - Downloaded data for ICX-PERP with length 31422.
2021-11-07 18:08:20,134 - freqtrade.data.history.history_utils - INFO - Downloading pair ICX-PERP, interval 1h.
2021-11-07 18:08:20,134 - freqtrade.data.history.history_utils - INFO - Download history data for pair: "ICX-PERP" (54/54), timeframe: 1h and store in user_data_futures_ftx/data/ftx.
2021-11-07 18:08:22,123 - freqtrade.exchange.exchange - INFO - Downloaded data for ICX-PERP with length 2620.
2021-11-07 18:08:22,137 - freqtrade.data.history.history_utils - INFO - Downloading pair ICX-PERP, interval 1d.
2021-11-07 18:08:22,138 - freqtrade.data.history.history_utils - INFO - Download history data for pair: "ICX-PERP" (54/54), timeframe: 1d and store in user_data_futures_ftx/data/ftx.
2021-11-07 18:08:22,611 - freqtrade.exchange.exchange - INFO - Downloaded data for ICX-PERP with length 110.
```
Getting these warnings for every pair that i download data for.

**Comment by xmatthias** [comment]
> 
> 
> ```
> /home/rk/src/freqtrade/venv/lib/python3.9/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'ICX-PERP'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
>   check_attribute_name(name)
> 2021-11-07 18:08:01,957 - freqtrade.data.history.history_utils - INFO - Downloading pair ICX-PERP, interval 5m.
> 2021-11-07 18:08:01,957 - freqtrade.data.history.history_utils - INFO - Download history data for pair: "ICX-PERP" (54/54), timeframe: 5m and store in user_data_futures_ftx/data/ftx.
> 2021-11-07 18:08:20,092 - freqtrade.exchange.exchange - INFO - Downloaded data for ICX-PERP with length 31422.
> 2021-11-07 18:08:20,134 - freqtrade.data.history.history_utils - INFO - Downloading pair ICX-PERP, interval 1h.
> 2021-11-07 18:08:20,134 - freqtrade.data.history.history_utils - INFO - Download history data for pair: "ICX-PERP" (54/54), timeframe: 1h and store in user_data_futures_ftx/data/ftx.
> 2021-11-07 18:08:22,123 - freqtrade.exchange.exchange - INFO - Downloaded data for ICX-PERP with length 2620.
> 2021-11-07 18:08:22,137 - freqtrade.data.history.history_utils - INFO - Downloading pair ICX-PERP, interval 1d.
> 2021-11-07 18:08:22,138 - freqtrade.data.history.history_utils - INFO - Download history data for pair: "ICX-PERP" (54/54), timeframe: 1d and store in user_data_futures_ftx/data/ftx.
> 2021-11-07 18:08:22,611 - freqtrade.exchange.exchange - INFO - Downloaded data for ICX-PERP with length 110.
> ```
> 
> Getting these warnings for every pair that i download data for.

you are aware that this PR does NOT deal with downloading, only with detecting them as potentially valid pairs. ... so i'm not sure what you're downloading ... (check #5780 for this).
probably needless to say - it's not really related to this PR.

**Comment by kroitor** [comment]
@xmatthias jfyi, we're going to use this naming schema: https://github.com/ccxt/ccxt/wiki/Manual#contract-naming-conventions

**Comment by xmatthias** [comment]
@kroitor i don't really see a problem with that - as we try to not give much meaning to the pair identifier itself - but rather rely on the content of `markets`.

will that mean that you will convert `XTZ-1231` (that's a valid FTX futures asset, which is currently returned as `XTZ-1231`) to `XTZ/USD:USD-211231`?

**Comment by kroitor** [comment]
> @kroitor i don't really see a problem with that - as we try to not give much meaning to the pair identifier itself - but rather rely on the content of `markets`.

Great!

> will that mean that you will convert `XTZ-1231` (that's a valid FTX futures asset, which is currently returned as `XTZ-1231`) to `XTZ/USD:USD-211231`?

Yes, eventually, but in our design `XTZ-1231` will still work as a unified symbol, cause you can now supply a market id in the `symbol` argument to any unified method. So, this transition will be performed in a non-breaking manner.

**Pull request merged**
