### PR TITLE
Allow use of --strategy-list with freqai, with warning

### PR DESCRIPTION
**Pull request by paranoidandy**
## Summary

Trying to run backtesting with freqai and multiple strategies via `--strategy-list` currently exits with an `OperationalException`. This PR changes this to allow backtesting multiple strategies in one command, but with a user warning that all strategies must share identical `populate_any_indicators`.

## Quick changelog

- Replace raising `OperationalException` with a user warning.
- Rewrite test.freqai.test_freqai_backtesting.test_freqai_backtest_start_backtest_list to assert the warning is produced.

### CODE REVIEW

**Comment by xmatthias** [comment]
@robcaulk wouldn't a side-effect of this be that `freqai.start()` is called twice in backtesting? (once per strategy).

so in unlucky cases, this might mean that the model is trained twice ... no? (this was the main reason to disable this in the first place).

**Comment by robcaulk** [comment]
> @robcaulk wouldn't a side-effect of this be that `freqai.start()` is called twice in backtesting? (once per strategy).
> 
> so in unlucky cases, this might mean that the model is trained twice ... no? (this was the main reason to disable this in the first place).

With the new prediction saving feature, all subsequent calls to `freqai.start()` will just load the predictions from disk. This is why we decided to try to bring this feature back. This is also why it warns that `populate_any_indicators is **REQUIRED** to be the same across all strategies`

Now I am thinking about ways to enforce it beyond just giving the user a warning.

**Review by xmatthias — APPROVED** [review]
For me that's fine - obviously having a way to enforce it would be better - but i guess not required right away.

**Review by robcaulk — APPROVED** [review]
Good to go

**Comment by robcaulk** [comment]
> For me that's fine - obviously having a way to enforce it would be better - but i guess not required right away.


We now enforce identical `populate_any_indicators` by loading in the metadata from the existing training and comparing feature lists to current dataframe.

**Pull request merged**
