### PR TITLE
New release 2020.5

### LINKED ISSUE #3378: Crash: Timestamp subtraction must have the same timezones or no timezones
## Describe your environment

  * Operating system: Linux
  * Freqtrade Version (docker-compose): freqtrade docker-b50d072d

## Describe the problem:

Recently I pulled new docker image and sometimes bot is crashing on data fillup. Note that I didn't do any actions with timezones or settings, it is a bug that came with the update. I'm using kraken exchage.

## Logs:
```
2020-05-26 04:21:20,354 - freqtrade.data.converter - INFO - Missing data fillup for OMG/BTC: before: 631 - after: 719
2020-05-26 04:21:20,905 - freqtrade.commands.trade_commands - ERROR - Timestamp subtraction must have the same timezones or no timezones
2020-05-26 04:21:20,905 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
File "/freqtrade/freqtrade/commands/trade_commands.py"
, line 20, in start_trading

worker.run()
File "/freqtrade/freqtrade/worker.py", line 73, in run

state = self._worker(old_state=state)
  File "/freqtrade/freqtrade/worker.py", line 107, in _worker

self._throttle(func=self._process_running, throttle_
secs=self._throttle_secs)
File "/freqtrade/freqtrade/worker.py", line 128, in _t
hrottle

result = func(*args, **kwargs)
File "/freqtrade/freqtrade/worker.py", line 141, in _p
rocess_running
self.freqtrade.process()
  File "/freqtrade/freqtrade/freqtradebot.py", line 167, in process

self.enter_positions()
File "/freqtrade/freqtrade/freqtradebot.py", line 233, in enter_positions
trades_created += self.create_trade(pair)
File "/freqtrade/freqtrade/freqtradebot.py", line 416, in create_trade
(buy, sell) = self.strategy.get_signal(
File "/freqtrade/freqtrade/strategy/interface.py", line 338, in get_signal
(arrow.utcnow() - latest_date).seconds // 60
File "/usr/local/lib/python3.8/site-packages/arrow/arrow.py", line 1147, in sub
return self._datetime - other
File "pandas/_libs/tslibs/c_timestamp.pyx", line 300, in pandas._libs.tslibs.c_timestamp._Timestamp.__sub__
TypeError: Timestamp subtraction must have the same timezones or no timezones
```

### PR DESCRIPTION
**Pull request by xmatthias**
## Highlighted changes

* Complete rework of fee handling - which now detects "other currency" fees like BNB (Binance) and FEE (Kraken) percentages correctly (which are usually lower than the default). 
  * This also "guesses" the close fee to be identical to the open fee - allowing for better calculation.
  * "eat dust" feature added (automatically done when fees are paid in base currency) - preventing dust from piling up (Dust = unsellable low amounts of currencies).
* Addition of [`ShuffleFilter`](https://www.freqtrade.io/en/latest/configuration/#shufflefilter) to randomly shuffle your pairs in the pairlist.
* New `cancel_open_orders_on_exit` setting to allow cancelling open buy / sell orders when the bot exits.
* Addition of `ticker` to [dataprovider](https://www.freqtrade.io/en/latest/strategy-customization/#possible-options-for-dataprovider).
* Addition of `current_whitelist` to [dataprovider](https://www.freqtrade.io/en/latest/strategy-customization/#possible-options-for-dataprovider).
* New subcommand, `show-trades` to quickly visualize one or more trades.
* Hyperopt CSV export now exports found parameters in additional columns.
* Fix anoying bug causing notifications to spam if a sell-order was partially filled.
* Improved Fee handling in Edge - causing more precise results for win ratio and expectations.
* Add CORS support to REST API (important for [freqUI](https://github.com/freqtrade/frequi) - warning - this is still in early alpha!)
* Add JWT support to improve security of the API.
* The freqtrade internal storage format for downloaded trades/ticks data (those that fetched with `--dl-trades`, for Kraken) has been changed. This solves problems with exhausting memory when downloading OHLCVs for highly active markets like BTC/USD from Kraken.
* The version of pandas bumped to 1.0.4. This release of pandas resolves a memory leak in `rolling().max()`/`rolling().min()`  you may experience in indicators built with the use of these methods (including indicators from third-party libraries).

### How to update

As always, you can update your bot using one of the following commands:

#### docker-compose

```bash
docker pull freqtradeorg/freqtrade:master
docker-compose up -d
```

#### Installation via setup script

```
# Deactivate venv and run 
./setup.sh --update
```

#### Plain native installation

```
git pull
pip install -U -r requirements.txt
```

<details>
<summary>Expand full changelog</summary>
```
95780cb4 Version bump to 2020.5
7df78699 Plotting should not fail if one pair didn't produce any trades
cb40e850 Add question template ...
18a5787a Reorder typing imports
b2125bd6 check for None to allow 0.0 profit
f4af4cc2 Small formatting improvement
8c87fcda Rename PricingException to PricingError
16cd1f06 Rename get_order_book to fetch_l2_order_book (aligning to ccxt)
d09a3478 Add tests for pricingexception
7a7b26e8 Add exception handlers for orderbook logic
76e4e589 Introduce pricing exception
bdf795b8 final cleanup - use different cache image for now
3e3cce45 Use pct instead of _perc
448546b0 Some cleanup in script
2f596f73 Use cache correctly
27e0c260 Add comment to ensure we're not accidentally removing this again
500ce501 Switch to docker experimental ...
7f5feab5 Fix notifications, build ...
571d61de Cancel previous automatically?
4fbd2deb Use correct image
a7c0e86b Test rpi using buildx and dockerfile.armhf
9f573481 Fix #3378
18d25878 Address feedback
abf79e4a Use temporary variable to clean up code
6a9a8f92 Rename some methods, improve some testing
462c35cf Move stats generation to the top
46f1470e Fix failing test
027ea64d Fix docstrings, extract strategy-list results
db257e9f Rename method to be public
18a2dad6 Extract data generation from generate_text_table
0917b17e Refactor result_line to return dict
5c5dce52 Bump flake8 from 3.8.1 to 3.8.2
1c9103a1 Bump ccxt from 1.27.91 to 1.28.49
781de767 Bump mkdocs-material from 5.1.7 to 5.2.1
6eba7186 Bump pytest-cov from 2.8.1 to 2.9.0
e1362755 Add test for sell_reason_stats
876a9e4f finish refactor of sell_reason table
d17300fd Refactor sell reason stats to return a dict
9d1ad70b Split optimize generation from printing
8217d92a UPdate version question
e138f9b2 Apply suggestions from code review
aa004fa8 Fix typo in label
c5480c25 Split issue-tempaltes
bbd7579a Fix more tests
811e23e3 Have profit return time in timestamp
859b619a Align tests to new output
110b5a25 Add timestamp to trade output
73914169 Update issue template
046202fd Fix typing circular dependency
073d9d38 Update readme.md with adjusted sequence
98db1d52 Reorder new commands
43e2bce6 Update readme with current command list
1663a679 Reorder list-arguments
33b270b8 reorder more arguments
fcae48d5 Some reordering of subcommands
cd0bf96c Improve pairlist tests
1f386c57 Don't start plotting profit without trades
1a984ac6 Explicitly raise ValueError if trades are empty
3b5ccf2e Fix documentation link
a11651ae Correctly test cors
4f0d9281 Introduce self._enabled in pairlist handlers
7e435743 Refactor filter_pairlist()
2fbd31f5 CORS - allow authenticated responses
2498fa5a Bump scikit-learn from 0.22.2.post1 to 0.23.1
696c7e87 Use proper logging (using the Filter's logger)
e96e28df Refactor verify_blacklist()
a8b1dcf3 Minor: cleanup in get_signal()
4c4fb0c9 Cleanup in pairlistmanager
d8352bd6 Fix tests for SpreadFilter
30d1a858 Adjust docs
2c6c287c Address comments made in review
115586a5 Introduce freqtrade.typing
6951b20a Do not throttle with DependencyException in retrier
8bdd5e71 Minor: correct import of retrier
0c8aff98 Make flake happy
a0c9f7ba Bump scikit-learn from 0.22.2.post1 to 0.23.0
627c5059 Move create_pair_list to pairlistmanager
f54dc7af Make flake happy
cc28aae5 Fix the links again
5a9a3135 Adjust empty f-strings to be non-fstrings
d57ef6a2 Pairlist Section reworked
601cbd12 Bump ccxt from 1.27.49 to 1.27.91
ff8e85f2 Bump sqlalchemy from 1.3.16 to 1.3.17
7d80f8d2 Fix links in docs
37a10d1d Bump joblib from 0.14.1 to 0.15.1
a447efbe Bump mkdocs-material from 5.1.6 to 5.1.7
37fd675a Bump flake8 from 3.7.9 to 3.8.1
51c0639e Update tests/pairlist/test_pairlist.py
503a8a82 Simplify sd_notify usage
287e8baf Add/adjust tests
4bfab5e2 Add ShuffleFilter
64b8d8c7 Use correct Return hint
943a2a08 Improve daily API format
16622bbf Cosmetics in pair lists
ae69d310 Cosmetics in IPairList
97c50f86 Cleanup pairlistmanager
285bc251 Improve testcov for default check_*_timeout methods
2074d986 Update test to verify we're not spamming messages
dd55d2ee Reduce spammyness of parcial cancel orders
1e76bff1 Add sell_order_status to keep track of cancellations
ce185a3b Remove pairs with no ticker available when it's needed
d457542d Fix PrecisionFilter
baf5f4f2 Update freqtrade/constants.py
5f2a8716 Add missing module
fed75d87 remove --cancel_open_orders cli switch
7a11219b Reword some documentation strings
22a08768 Add test for cancel_open_order
e7c11ed2 Fix fetching timeframe (failed in backtesting)
facaaabc Rename _refresh_whitelist()
f8b01f5a Make flake happy
035a12ce Move _create_pair_whitelist to dataprovider
bf257469 Introduce datatype for informative pairs
c3f3242f Add tests for cancel_open_orders_on_exit
1b3864eb Make flake happy
61f6acb5 Add cors support - needed for UI
ac076ee0 Update docs/strategy-customization.md
d84cb3be Improve test
06b12c0a Add warning to docs for ticker data
323b4919 Add description and example for dp.ticker() to the docs
33091f95 Bump python from 3.8.2-slim-buster to 3.8.3-slim-buster
a7b469e8 Add test verifying correct price reduction on limit stoploss orders
92b6d3e2 Adjust test to reflect correct behaviour
143e6f52 Simplify SpreadFilter
cbb2ce37 Simplify PriceFilter
2aa80f91 Cosmetics: improve readability
794ed304 Make stoploss an attribute
afa7a584 Simplify PriceFilter
f0c3a0d2 Simplify VolumePairList
2924b70f Cosmetics in tests/pairlist/
481f9ba6 Use list comprehension instead of filter()
fb92300c Update docs/docker.md
78b81bac Add test for dp.ticker()
38fd361c Add note about PI and docker
aae096c6 Handle fetching ticker for non-existing pair safe way
ced81266 Minor fix in the strategy docs
255ff6cd Should return False if it's not been cancelled empty
60f26ba5 use update_trade_state also for closed stoploss orders
b3dd0a68 minor: fix typo in configuration.md
6ff457e3 Update doc Ta_lib
6e86a477 updated docs
fe3ea8e7 Fix stoploss on binance bug
0c3bdd66 Update sql cheatsheet iwth current table structure
63dfe366 Updated docs for #3267
f1367b38 Docs: Fix the fix
77c9334c Use available config object
e2b9c248 Docs: Fix sample in strategy-advanced
aa25461e Show forcebuy status so it's visible before calling forcebuy.
e864db18 Update test for dp.current_whitelist
25807192 Correct log path in doc.
c8f3ef88 Minor: Add filterwarning for DeprecationWarning in test
9fbe1357 attached pairlist manager onto dataprovider init for unified access to dynamic whitelist
a5bfa551 Fix flake8 mypy
bc9efc31 Added Method for accessing current pair list on initialization for dynamic informative pairs
a8f523ad attached pairlist manager onto dataprovider init for unified access to dynamic whitelist
a379e68c Add new ta-lib wheels
96710d42 Bump mkdocs-material from 5.1.5 to 5.1.6
e38581c1 Bump plotly from 4.6.0 to 4.7.1
43ab814f Bump ccxt from 1.27.20 to 1.27.49
3849b68b Bump ta-lib from 0.4.17 to 0.4.18
306eae6d Bump pytest from 5.4.1 to 5.4.2
9eca268a Fix test
d291ca00 Simplify code section
21c2af2b Load jwt_key from config
c3f0b5d4 Rename methods to match endpoints
b163bb76 Apply suggestions from code review
c2224ed6 Fix doc typos
73a14963 Catch exception on cancel_order
2406e20b Update docs/rest-api.md
80faa5fe Add test to cancel sell order
d9e4f41a Add documentation for JWt
570c51b0 Fix Typo in telegram Plugin
51d2b817 Use self.fee
bc64619f Tests for JWT implementation
8139058f Implement token/login and token/refresh endpoints
0bd2fca4 Update tests/test_integration.py
b6a2c389 Adjust tests
7e08fa26 Fix usage of fee value in Edge
b72997fc Add flask-jwt-extended dependency
d4362ed3 Minor: improve exception handling in exchange
2307495f Update docs/configuration.md
80d367fa Add test for keyboardinterrupt
5272ec85 Add additional test
c560de41 Improve exception handling on critical errors
1ba2df79 Ause isclose for comparison, assign filled to variable
a62d7495 FIx typo in telegram method
593d13eb Show new values also in Telegram
e4023a65 Add some minor things to show_config
ffef4bc4 Humanize show-trades error when no database is specified
d3a0ab80 Change mock-status to be open when testing unfilled...
98197668 Use filled, it's the safer choice when determining the filled amount.
b4aeb93a Add test testing the different ways exchanges may return data
f040c206 Use filled in tests
648723fb Use 30min rate cache
5dde6d3f Bump python-telegram-bot from 12.6.1 to 12.7
32eb1c57 Bump mkdocs-material from 5.1.3 to 5.1.5
611b9c88 Bump ccxt from 1.27.1 to 1.27.20
2c352e6b Bump progressbar2 from 3.51.0 to 3.51.3
68f0b105 Bump pytest-asyncio from 0.11.0 to 0.12.0
a14e027a Bump arrow from 0.15.5 to 0.15.6
f7a3bb82 Bump numpy from 1.18.3 to 1.18.4
b38f9ed5 Increase cache for rate limit to avoid delays
2a4c9bf3 Improve logmessage when falling back to wallet amount
889a1537 fix PEP8
690bb764 hyperopt csv export - add params
1c9c7293 Adjust trade-ids param
e92d3867 Fix failing test
81397874 Remove commented mock
72282a22 Add explicit test for fee_conditional
58168336 Add test for apply_fee_conditional
38c49493 Align applying of fee when comming from orders or trades
7dcef58f Add show-trades to documentation
1066a450 Add test for show_trades
56bb5f7a Add show-trades command
78b3d848 Add typehint
021e2b58 Support partially cancelled orders for fee calculation
737fc6d1 Fix bug when querying side
71c90422 Add explicit test for fee_updated
6d620ba1 Verify if fee for this side has been updated
6b33d5af Fix fee-calculation for dry-run orders
bd51cd33 Cancel all open orders after receiving /stop or ctrl+c
509f38d3 Use non-deprectated parameter for progressbar
40d4949f Don't handle trades if they've just been closed.
7558e4bf Split fee detection from trades from general logic
371100a9 Update fee handling
a2ff6326 Add update_fee method to persistence
fdcc507f Fix integration tests
b93d33a9 Fix mock order dicts
db8fb39a don't use trade.update directly!
59bafc8d Implement fee rate calculation
45c97fde Use correct typehint for extract_cost_curr_rate
f8f794a8 Simplify  fee-related tests
63b55658 Add ticker to dataprovider
e74ed0ba Add tests for fee extraction methods
2e4dc6c2 Exchange should return fee dict for dry-run orders
a867d40e Move fee_methods to exchange
d3b9f4d3 Add extract_cost_curr_rate
6d7a3a0c Extract more logic into order-has_fee
b125dd37 Extract order_has_fee method
7936120a Adapt tests to support new db fields
dec1b107 Add fee_cost and currency columns
38c6ba6c Update setup.py
9152e769 Add skopt version check into setup.py
69b44234 Update docs/backtesting.md
74281a16 Move to the last point and clarify further
1a6ddfca Be clear on evaluation logic during backtesting
726e52aa Use skopt model_queue_size instead of custom hack
c6787d7e Do not use 'trials' in commands
c2683504 Hyperopt cleanup, do not use 'trials'
a01ed170 Improve hyperopt-list logging
3754bf46 Change wording in deprecation messages
fb8a85da Disallow VolumePairList from backtesting for now
9fa21628 Deprecate keys other than quoteVolume
d1a24db6 Remove deprecated pairlist and binary
e8530c36 Remove pairlists from hyperopt too (it holds a reference to exchange)
57345476 Document pairlists for backtesting
89878590 Enable pairlist parsing for backtesting and hyperopt
7aba9bc6 Update freqtrade/data/converter.py
46f1d1f3 Failing test might be incompatibility
9d7ad23d Fix test leakage
eab6c9c5 Fix message
0d51383b Format logmessages correctly
5739ee6e Add test for trades data conversation
437d4cda Add test data for trades
ba03d969 Test 5s offset on since
ff9caf79 remove trade duplicates in datahandler
0506caf9 Implement trades_remove_dulicates
59f1a061 adapt exchange tests to use lists instead of dicts
b95e9fe3 Fix mocks to return correct things
bac0eaab fix convert to ohlcv
d76bb1cc Use List of Lists instead of list of Dicts for trades data
1659ddcc Add conversion function from fetch_trades to list
8bfbbac7 Add default trades columns
```
</details>

### CODE REVIEW

**Comment by hroff-1902** [comment]
^^ Made cosmetic fixes to the text above

Should we wait till pandas 1.0.4 and include it as the updated dependency?

**Comment by hroff-1902** [comment]
Other candidates to be mentioned in the Highlighted changes (from pinned news messages at Slack, yes, we have much more significant changes made):

* "The fee handling was slightly fixed in the Edge module, so if you use pairlist/stoploss values based on results of your previous Edge runs on historical data, you may wish to review the results.
Update if you use Edge in the dry-run/live trade mode, it will now produce more correct results for win ratio and expectations."
* "Freqtrade REST API server now supports JWT tokens for authorization, which improves security if you establish your REST API server into the internet. See https://www.freqtrade.io/en/latest/rest-api/#advanced-api-usage-using-jwt-tokens"
* "The hyperopt-list subcommand with the --export-csv option now exports the values of the hyperspace dimensions used for each epoch printed."
* "The freqtrade internal storage format for downloaded trades/ticks data (those that fetched with --dl-trades, for Kraken) has been changed. This solves problems with exhausting memory when downloading OHLCVs for highly active markets like BTC/USD from Kraken.
The switch to the new trade-format is automatic once download-data is ran for the first time after update. However switching back to the earlier version of data format is impossible, requires complete re-downloading of all trades data.
A manual conversion can be done via the following command: freqtrade convert-trade-data --format-from jsongz --format-to jsongz --datadir user_data/data/kraken.
Again, switching back to the old trades format is NOT possible if you decide to return back to the previous develop or move to the current master from develop. (Next master release will also contain this fix though.)
Update if you are working with the Kraken exchange data."
* "Handling of exchange fee for executed orders has been significantly reworked in freqtrade. This includes several fixes for fee-related issues we've got recently (April) and in December. This also allows freqtrade to "eat" currency dust (see Binance Dust) if fee is payed from the base currency."
* "The new cancel_open_orders_on_exit setting was added into config."

**Comment by xmatthias** [comment]
> ^^ Made cosmetic fixes to the text above
> 
> Should we wait till pandas 1.0.4 and include it as the updated dependency?

Do many fixes as you feel needed. it's just a proposal most of the time - and for the release, i'm alwasy copy/pasting the latest version of the initial post.

I'm not sure - i'm not a huge proponent of waiting on dependencies - i can force-update in this branch to 1.0.4.
But it might be a bad idea, considering it's a brandnew release (released yesterday...) - so maybe the day after tomorrow we (or someone else) discovers a heavy bug in pandas which will break "something else" we didn't see comming...

**Comment by hroff-1902** [comment]
Let's update forcibly pandas in develop, test it a bit, and wait this release for pandas included into it as well.

**Comment by hroff-1902** [comment]
this: https://github.com/freqtrade/freqtrade/issues/3404#issuecomment-636446434
can be considered as a stopper for this release

**Comment by xmatthias** [comment]
> this: [#3404 (comment)](https://github.com/freqtrade/freqtrade/issues/3404#issuecomment-636446434)
> can be considered as a stopper for this release

Not unless we're able to reproduce it reliably. more comments regarding this in the issue.

**Comment by hroff-1902** [comment]
okay, my suspicion was that #3404 was introduced by pandas 1,0,4, that's why I decided to recall the approvement. Let's manage that later

**Comment by pnmartinez** [comment]
Hello everyone.

Nice release! Having the major rework on fees, I am trying to wrap my head around it without room for uncertainty before going live.

So, about the **eat Dust** method:

> "eat dust" feature added (automatically done when fees are paid in base currency) - preventing dust from piling up (Dust = unsellable low amounts of currencies).

What exactly is the mentioned "*base currency*"? Is it the "*stake currency*" defined on the configuración file? Because I am implicitly understanding that is the case, but then the system would only eat (let's say BTC is the stake currency) BTC dust - which is no dust at all! 

I would guess that the system would work in the case "eat dust" substracts from the "target currency", strictly dependant on the trade done, and non-settable on the config.

Docs are obviously not updated for this new recent fee handling, but I'll be able to help in that matter once I have all these points clear.

Thanks in advance!

**Comment by xmatthias** [comment]
the dust problem is mainly a binance (if you don't use BNB fees) and FTX problem.

Assume you buy 10 XYZ and don't own BNB (or have BNB fees disabled). Then fees will be reduced from XYZ (target currency), leaving you with 9.9 XYZ. However, you can only sell full XYZ - so 0.9XYZ are left in your account as Dust.

The same thing will happen on sell - (you sell 9 XYZ, should get 0.1 BTC, but you really get 0.09999 BTC. This is not strictly dust - but the problem is the same.

Now the next buy of 10 XYZ would have the same problem - HOWEVER, this time, the bot will be able to sell 10 XYZ, because you now don't own 9.9XYZ, but 10.9XYZ, so selling 10 XYZ is possible. (it eats into the dust - using the existing 0.9 XYZ to pay fees).

Again, on sell, you'll not get 0.1 BTC, but 0.09999 BTC - but there is nothing freqtrade can do against this, as it's how binance works - but profit calculations do account for this before selling.

The big change is to recognize the existing 0.9 XYZ, and not accumulate dust (prior to this version, you'd have had 1.8 XYZ in your account).

Hope this makes sense.

**Comment by pnmartinez** [comment]
> the dust problem is mainly a binance (if you don't use BNB fees) and FTX problem.
> 
> Assume you buy 10 XYZ and don't own BNB (or have BNB fees disabled). Then fees will be reduced from XYZ (target currency), leaving you with 9.9 XYZ. However, you can only sell full XYZ - so 0.9XYZ are left in your account as Dust.
> 
> The same thing will happen on sell - (you sell 9 XYZ, should get 0.1 BTC, but you really get 0.09999 BTC. This is not strictly dust - but the problem is the same.
> 
> Now the next buy of 10 XYZ would have the same problem - HOWEVER, this time, the bot will be able to sell 10 XYZ, because you now don't own 9.9XYZ, but 10.9XYZ, so selling 10 XYZ is possible. (it eats into the dust - using the existing 0.9 XYZ to pay fees).
> 
> Again, on sell, you'll not get 0.1 BTC, but 0.09999 BTC - but there is nothing freqtrade can do against this, as it's how binance works - but profit calculations do account for this before selling.
> 
> The big change is to recognize the existing 0.9 XYZ, and not accumulate dust (prior to this version, you'd have had 1.8 XYZ in your account).
> 
> Hope this makes sense.

This totally makes sense. I guess all the naming got me confused ("base currency", "stake currency", "target currency"...). We have to be careful when using those informally! Specially in the docs.

Looking forward to see this change in the docs: in my opinion it solves major, problematic issues.

Gonna switch to prod today and will report back. Cheers!

**Comment by xmatthias** [comment]
well - target currency is the correct term for fees on binance - as it'll always subtract from the currency you're receiving (XYZ when buying XYZ/BTC, BTC when selling XYZ/BTC).

**Comment by pnmartinez** [comment]
Ok, I see. I think you've made pretty much clear! So with **base currency** you meant that same **target currency**, right?

> "eat dust" feature added (automatically done when fees are paid in base currency)

**Pull request merged**
