### PR TITLE
#10455 - Install local freq UI build

### PR DESCRIPTION
**Pull request by haxwell**
## Summary

This PR allows the install_ui command to install a local build of freq-ui.

Solve the issue: #10455 

## Quick changelog

commit 377cb0d46a362fe8af893a23c98c3a3767238a0a
Author: Johnathan James <haxwell@gmail.com>
Date:   Tue Jul 23 11:19:15 2024 -0600

    install-ui can read a local build of freq-ui
    
    Pass the param --local_source with the path to a zip of your freq-ui
    dest directory. This director is created after you run 'pnpm run build'
    on the front end. You would then zip the directory with 'cd dist && zip
    -r dist.zip .'.

jjames@hppav06:~/src/freqtrade/freqtrade$ git diff --name-status install-local-freq-ui-build..develop
    M       freqtrade/commands/arguments.py
    M       freqtrade/commands/cli_options.py
    M       freqtrade/commands/deploy_commands.py
    M       tests/commands/test_commands.py

## What's new?

This PR allows the user to supply a locally built zip file containing the production build of freq-ui, and install it in the (usually development) instance of freqtrade.

### CODE REVIEW

**Comment by xmatthias** [comment]
Please refer to the comment in the linked issue.

I don't really see a reason for having this - so it's just adding unnecessary code for your individual usage.

Please provide a **compelling** reason why this would be needed (not just for yourself, but for other users, too) - otherwise, i don't see a point in this PR - and hence also no real reason to do a proper review.

**Comment by haxwell** [comment]
This PR makes it easier/faster/more efficient to iterate by making changes in freq-ui, and then seeing them in a running instance of freqtrade. If a developer is doing any work in freq-ui, they will be making frequent changes. This PR lowers the cost of each of those iterations.

The developer 

1. makes their change in freq-ui, 
2. builds and zips it up (because that's how a production release would be distributed), 
3. runs install-ui again. 

Any developer working on freq-ui could make use of this feature. If not, they are doing something much more manual, and error-prone to accomplish the same thing.

**Comment by haxwell** [comment]
Closing, you don't need to install freq-ui in the freq-trade server to see your changes. Running `pnpm run dev` is enough, and it communicates with a running freq-trade server.

**Comment by xmatthias** [comment]
running "stop, build, zip, install, run" (you need to shutdown freqtrade to run the install command) is WAY slower than running a parallel devserver - which will benefit from hot-reloads (you can change "most" of the things in freqUI without reloading the page) - so from a DX perspective - this would be a pretty bad way.


Glad that running `pnpm run dev` is what you're actually after :+1:

**Pull request closed without merging**
