### PR TITLE
Wins/draws/losses/median profit in hyperopt output

### PR DESCRIPTION
**Pull request by yazeed**
This PR suggests a couple of additional info to the hyperopt output (wins/draws/losses, and median profit which kinda shows if your avg profit is skewed due to lucky trades in that epoch, it's a simple way to detect outlier trades in an epoch), it should support #2943 if that PR is merged into develop.

Let me know your thoughts.

Will work on the tests once thoughts are finalized into this.

### CODE REVIEW

**Comment by hroff-1902** [comment]
That's fine, but the overall length is longer than the width of my terminal, so printed in two lines...
Should look better in the tabular format.
Shall we merge it now, or wait for tabular format ready for hyperopt?

**Comment by yazeed** [comment]
> That's fine, but the overall length is longer than the width of my terminal, so printed in two lines...
> Should look better in the tabular format.
> Shall we merge it now, or wait for tabular format ready for hyperopt?

Let me finalize this, it needs it's own tests to be fully compliant.

**Comment by yazeed** [comment]
I don't know what happened here, I think I rebased to upstream/develop instead of local/develop before pushing.

**Comment by yazeed** [comment]
Closing, and duplicating at #3008 as I've messed this one up.

**Pull request closed without merging**
