### PR TITLE
Argument handling refactor

### PR DESCRIPTION
**Pull request by xmatthias**
## Summary
This should be a first step to get #1945. This is really necessary as the plot-scripts show 100ds of options, while only a fraction of them really works (e.g. Plot dataframe shows the whole backtesting arguments, but only --live and --refresh-pairs-cached are actually used)

Part of the issue: #1945

## Quick changelog

- Use dict of Arguments to "pick and choose" using lists.
- Each argument is defined exactly once, and can be used at will by every subcommand.
- Kept only options that really work for plot-scripts

Technically, the PR is ready for review, however it should be merged AFTER #1957 to give us time to do further steps in #1945 

Edit: Rebased against develop to make sure none of the changes to helpstrings are missed.

### CODE REVIEW

**Comment by hroff-1902** [comment]
Fine. I thought it would be much heavier solution...

I have a couple of design questions we have to address here (or in a sep. PR), will post them a bit later in #1945...

**Comment by xmatthias** [comment]
Well it's a first step in #1945 - not the "end-goal" - but it allows "simple" reuse of arguments across different commands (it's really a requirement to "fix" the plot-scripts without creating 20 new "argument_*" functions).

**Comment by hroff-1902** [comment]
> without creating 20 new "argument_*" functions).

They (arguments) can be grouped however as I've done for load_common/load_main...

**Comment by xmatthias** [comment]
partly yes - but mainly the plot scripts use 2 or 3 from backtesting - but not the rest.
also i see this as a first step to move this out of arguments.py and into config - with default (which is not a default in the argument) ...

but everything at once would be even tougher to review

**Pull request merged**
