### PR TITLE
Sortino HyperOptLoss method

### PR DESCRIPTION
**Pull request by yazeed**
This is an incomplete PR that prepares for a Sortino HyperOpt Loss Method as mentioned in #2407, which seems to be able to come up with strategies with very low drawdowns (0.02 to 0.05), specially if you enable trailing stop loss.

**Work to be done:**
- [x] - SortinoHyperOptLoss: To be consistent with SharpeHyperOptLoss.
- [x] - SortinoHyperOptLossDaily: To be consistent with SharpeHyperOptLossDaily.
- [x] - Unit tests for both new hyperopts.

References:
- [Wikipedia: Sortino](https://en.wikipedia.org/wiki/Sortino_ratio)
- [Investopedia: Sortino](https://www.investopedia.com/terms/s/sortinoratio.asp)
- [Xplained: Sortino](https://xplaind.com/262577/sortino-ratio)
- [ProgrammingForFinance: Sortino](https://programmingforfinance.com/2017/11/examining-the-sortino-ratio/)

### CODE REVIEW

**Comment by hroff-1902** [comment]
* added WIP marker into the title
* added 'don't merge' label
-- you'll need to remove them back when you'll think the PR is ready for final review and merge.

**Comment by hroff-1902** [comment]
The question here is: shall we make a complementary (Sortino) metrics from broken legacy implementation of Sharpe, or start with the fixed brand new daily variant...

**Comment by yazeed** [comment]
> The question here is: shall we make a complementary (Sortino) metrics from broken legacy implementation of Sharpe, or start with the fixed brand new daily variant...

How about we provide both variants? As I witnessed different, both good in their own way, results with both sharpe methods.

**Comment by hroff-1902** [comment]
^^ https://github.com/freqtrade/freqtrade/pull/2856/commits/9cd6feaff5e4e4ade513f22e2f793ca92b8fcb90 👍

**Comment by yazeed** [comment]
> ^^ [9cd6fea](https://github.com/freqtrade/freqtrade/commit/9cd6feaff5e4e4ade513f22e2f793ca92b8fcb90) 👍 😉

That didn't really work, but I figured we need to fix it in a new PR for both daily testing methods, cause profit_percent_after_slippage wasn't visible to that method.

**Comment by hroff-1902** [comment]
should be rebased somehow, to remove all those initial commits that went from old develop, or something... I do not remember I commited to this branch...

maybe cherry-picked at the new base, now it's impossible to find the changes that are really relevant to this PR...

@yazeed I'll tell you how do I deal with my forked repo...

**Comment by yazeed** [comment]
> should be rebased somehow, to remove all those initial commits that went from old develop, or something... I do not remember I commited to this branch...
> 
> maybe cherry-picked at the new base, now it's impossible to find the changes that are really relevant to this PR...
> 
> @yazeed I'll tell you how do I deal with my forked repo...

Would a rebase to upstream develop and recommit or push work? Or do I need to remove actual commits from the feature's branch?

**Comment by yazeed** [comment]
Note to self: Once this is merged, I can work on fixing its tests in a new PR.

**Comment by xmatthias** [comment]
I really do wonder how you're updating a branch to the latest develop.

using `git merge develop` would cause a merge commit - but seems like all commits have been cherry-picked - which i don't belive.

rebase wouldn't do that either - that would simply apply your latest commits on top of develop.

I suspect that the "history" issue could be solved with an interactive rebase (`git rebase -i 0665248` - skipping / removing all commits between f8bb6a3 and 97e4808 from this branch.
You should then be able to either merge develop to this branch - or rebase this branch on top of develop ... either way - this history is very messed up...

**Comment by hroff-1902** [comment]
I'm usually merging develop from web, here in the PR page (usually merging after pushing and creation of PR when I see here below that there is conflict with current develop, no actually needs to merge before...)

**Comment by yazeed** [comment]
git fetch
git checkout develop
git show
git pull upstream develop && git push origin develop
git checkout feature
git rebase origin/develop
git commit -m "yo"
git push origin develop

> I really do wonder how you're updating a branch to the latest develop.
> 
> using `git merge develop` would cause a merge commit - but seems like all commits have been cherry-picked - which i don't belive.
> 
> rebase wouldn't do that either - that would simply apply your latest commits on top of develop.
> 
> I suspect that the "history" issue could be solved with an interactive rebase (`git rebase -i 0665248` - skipping / removing all commits between [f8bb6a3](https://github.com/freqtrade/freqtrade/commit/f8bb6a3e065f53695b5df28190b4dbf54623ea56) and [97e4808](https://github.com/freqtrade/freqtrade/commit/97e48080e8601dcf692e687f0c4f7de747cce62e) from this branch.
> You should then be able to either merge develop to this branch - or rebase this branch on top of develop ... either way - this history is very messed up...

Not sure how all those arrived here, but here's my typical flow:

git fetch
git checkout develop
git show
git pull upstream develop && git push origin develop
git checkout feature
git rebase origin/develop
git commit -m "yo"
git push origin develop

**Comment by xmatthias** [comment]
well with #2879 now in a "cleaner state" - i hope you don't mind me closing this PR.

I will however copy/paste the "initial statement/comment" to the new PR - as i think that includes interresting information!

**Comment by hroff-1902** [comment]
> I will however copy/paste the "initial statement/comment" to the new PR - as i think that includes interresting information!

yes, thanks!

**Pull request closed without merging**
