### PR TITLE
Rename --custom-hyperopt to --hyperopt

### PR DESCRIPTION
**Pull request by xmatthias**
## Summary
Align --hyperopt specification to other commands (don't use --custom

Solve the issue: https://github.com/freqtrade/freqtrade/pull/2264#issuecomment-540287648

### CODE REVIEW

**Comment by hroff-1902** [comment]
I also do not like double `hyperopt --hyperopt`...

As an idea: `freqtrade hyperopt --hyperopt-class SampleHyperOpt --strategy-class SampleStrategy --hyperopt-loss-class DefaultHyperOptLoss`, these options may have the legacy `-s/--strategy`, `--hyperopt-loss` and the new `--hyperopt` aliases (the full form `--hyperopt-class`, `--strategy-class` is to be used in the docs), so the user could reduce the command line to `freqtrade hyperopt --hyperopt SampleHyperOpt --strategy SampleStrategy --hyperopt-loss DefaultHyperOptLoss` (and obtain double 'hyperopt' in the command), but this will be her choice...

**Comment by xmatthias** [comment]
I'm not sure about `--strategy-class` and `--hyperopt-loss-class` ... isn't this just "changing" because of the change?

i mean, sure, we can reword every command - but to what point or extend? 
The helpstring indicates that it's expecting a class already - we're also not renaming `--enable-position-stacking` to `--enable-position-stacking-bool` to indicate that it's a boolean flag .. ? 

cli options should be as short as possible - beeing too verbose will make it difficult to type (correctly), and lead to frustration (not necessarily issues, but frustration because the command is wrong again).

**Comment by hroff-1902** [comment]
`class` there is not the type of the entity (like `-bool` would be), but describes that the value is the name of the class and not the name of the module, containing it...

LGTM 👍 . at least it's much better than with legacy `custom`...

**Comment by xmatthias** [comment]
let's be honest - using `freqtrade hyperopt --hyperopt Hyperopt` is an extreme example

`freqtrade hyperopt --config userconfig --strategy Whatever --hyperopt Hyperopt` is more realistic - and then it's not "that" odd ...

**Pull request merged**
