### PR TITLE
Feat/short

### LINKED ISSUE #892: No option to short, Limits bot to 50% potential, increased risk during bear as counter trend trading
Crypto markets experience both bull and bear periods mid / long term and up/down price movement intraday. 

A lack of capability to trade short during bear periods limits strategies to trading against the trend which is hard work and carries in increased risk. 

To be able to flip a position from long to short when day trading doubles to entry points opportunities. 

By way of examples: 

1. Longterm low risk trade:  A simple long term trend trade on hr4 would make 150% on 1 short/bear flip from Feb to April, and 60% on the following bull. 
2. Day trading example: Indicators flip to short at 7600, but no means to short BTC on the drop. 

1)
screen shot 2018-06-10 at 9 08 06 am
2)
screen shot 2018-06-10 at 9 10 36 am

### LINKED ISSUE #2183: Strategy interface change discussion - enable position management and short trading
I think I'll disclose here my current ideas on design solutions for position management and trading short functionality. 

It's not a simple task, so it can be done in a steps. My main idea is the following:

0) The position management rules (algo, calculations) should be a part of the custom strategy.
1) So, as the first step, the `populate_buy()` and `populate_sell()` should be composed into one method. The resulting method (say, `populate_signals()`) should populate and return a column in the resulting dataframe, say, `position` with 2 possible values: 1 for current 'buy' and '0' for current 'sell'.
1a) The current interface should be kept. So there may be a setting like `experimental.use_populate_signal` which will switch between using current `populate_buy`/`populate_sell` and new `populate_signals`
1b) The above can probably be implemented as a helper function, which fetches results of current `populate_buy`/`populate_sell` and creates that new single signal column.
2) As the next step, this value, returned by the populate_signal, should be allowed to be float. Treated as ratio of stake_amount. So 1.0 means buy one stake_amount, 2.0 -- average up, 0.0 -- sell open position, 0.5 -- buy one half of the defines stake_amount, -1.0 -- trade short (! huh? why not...)

The user should be able to have access to trades made previously, wallets to perform position management calculations.

And voila, we are there... Of course, besides changing the strategy interface, all this will require support for fractional stakes everywhere in fraqtradebot, exchange, edge, backtesting and so on...

### LINKED ISSUE #6579: How does freqtrade deal with filterType: MARKET_LOT_SIZE?
According to Binance Exchange Info:

Symbol, maxQty MARKET_LOT_SIZE (As-is BTC Worth)
PROMBTC , 0.573570141462135
FLMBTC , 0.5679084474912659
MOVRBTC , 0.56226305882488
MDABTC , 0.5551352566504255
WOOBTC , 0.550690997831025
BNXBTC , 0.5415230872645199
QUICKBTC , 0.53345241231034
OAXBTC , 0.5248463292847095
FORTHBTC , 0.521943465386906
EPSBTC , 0.5044972909937301
MLNBTC , 0.5011197603760801
AUTOBTC , 0.500966687715
PHBBTC , 0.49321757126198235
KDABTC , 0.48172974260768203
GNOBTC , 0.42432694310363

In case when placing the market order within the above symbol list, if we take the market order of 1 BTC Worth within 1 order, the binance would not allow to place the order because the maximum volume must not exceed 0.42 - 0.57 BTC.

Regarding with this config setting:
    "order_types": {
        "buy": "limit",
        "sell": "limit",
        "emergencysell": "market",
        "forcebuy": "market",
        "forcesell": "market",
        "stoploss": "market",
        "stoploss_on_exchange": true,
        "stoploss_on_exchange_interval": 60
    },
    "bid_strategy": {
        "price_side": "ask",
        "ask_last_balance": 0,
        "use_order_book": false
    },
    "ask_strategy": {
        "price_side": "bid",
        "use_order_book": false
    },
    "exchange": {
        "name": "binance",
    }, ...

My quesiton is how freqtrade would circumvent with this situation:
If strategy decides to place a Stoploss Order on PROMBTC with 0.57 maxQty MARKET_LOT_SIZE, 

My first assumption is that the freqtrade break the main market order into 2 sub-orders: 0.57 and  0.43 BTC-worth market orders and then execute them.

My second assumption is that the freqtrade is aware of the MARKET_LOT_SIZE issues and then would place traditional stop limit orders until 1 BTC was fulfilled with 60-second-interval stop loss order updates.

Or the freqtrade would take the other assumptions, Please advise.

### PR DESCRIPTION
**Pull request by samgermain**
## Summary

Adds shorting and futures support to freqtrade

Solve the issue: 

https://github.com/freqtrade/freqtrade/issues/2183
https://github.com/freqtrade/freqtrade/issues/892
https://github.com/freqtrade/freqtrade/issues/5603
https://github.com/freqtrade/freqtrade/issues/5173
https://github.com/freqtrade/freqtrade/issues/2312
https://github.com/freqtrade/freqtrade-strategies/issues/151
https://github.com/freqtrade/freqtrade/issues/4109
https://github.com/freqtrade/freqtrade/issues/3848
https://github.com/freqtrade/freqtrade/issues/2942

## Quick changelog

- `trading_mode` in config to specify `spot` or `futures`
- `margin_mode` in config to specify `isolated` (cross not yet available)
- `populate_buy_trend` and `populate_sell_trend` changed to `populated_entry_trend` and `populate_exit_trend`
- strategies can short by specifying `exit_short` and `enter_short` in the `populate_entry_trend` and
`populate_exit_trend` strategy methods (`buy` and `sell` have been changed to `enter_long` and `exit_long`
- leverage can be used on trades using the strategies leverage method
- time_in_force `buy` and `sell` changed to `entry` and `exit` 
- liquidation price is calculated, and freqtrade keeps a price buffer on your trade to protect you from reaching the liquidation price
- gains/losses from funding fees are tracked
- Currently only works with linear markets
- Supported exchanges include Binance, Gateio, and Okex

### CODE REVIEW

**Comment by Rybarik1** [comment]
First of all, great job on this PR, it opens so many possibilities!

I've been testing it in the past few days and I'm unsure if calculation of stoploss with leverage is correct (both in backtesting and hyperopt). Does it represent the change in price or change to my account balance? 

**Example:** with leverage at 2.0 and stoploss at -0.02, is the stoploss triggered when price moves -1% or -2%? 

First option is what's implemented right now, but second one is more intuitive to me (so I wanted to know if it's a bug or a feature). If it's supposed to be the second option, then "profit" from triggered stoploss is calculated as if there was no leverage at all.

**Comment by xmatthias** [comment]
> **Example:** with leverage at 2.0 and stoploss at -0.02, is the stoploss triggered when price moves -1% or -2%?

It's intended to trigger after a move of -1% in this example.

The whole intend of stoploss is risk management. 
Your stoploss of -2% tells the bot "accept a maximum loss on the position of 2%" - which with leverage 2 - is a move of 1%. 

While it may seem more intuitive the other way - it's really not once you think it further.
If you're in a 5x position with a 10% stoploss - and suddenly wonder why the position is down 40% you'll know what i mean - as the stoploss would have accepted a loss of 50% of the original capital.

**Comment by Rybarik1** [comment]
Thanks for a quick and clear response. Another potential issue I've found is in calculation of max drawdown (both in backtesting and hyperopt). 
One strategy I tested had a starting balance of 1000usd and 3x leverage. In the first three months, all trades ended up as a loss, which equaled to -843usd. Then it recovers all the losses and continues profiting without any significant drawdowns. Both backtesting and hyperopt showed just 21% max. drawdown which would be correct if we ignored the first three months. Two possible explanations that came to my mind are

1. that max drawdown is recorded only after the first successful trade
2. that max drawdown is picked by highest nominal loss, not a percentual change in the account balance.

Didn't manage to find a strategy that would replicate this situation in the main branch, so I'm not 100% sure if it's exclusive to this PR.

**Comment by xmatthias** [comment]
The 2nd point is the case - and it's not something that changes by using leverage.

If you think it's something that needs fixing, please open a separate issue for that.

**Comment by samgermain** [comment]
@xmatthias Anything left?

**Review by xmatthias — APPROVED** [review]
I don't think that this will get any better at this stage.

We've tested it - we fixed a lot of problems/bugs - but there will always be more as more people use it.

As such - LGTM :+1: 

A huge thanks to @samgermain  for the big junk of work done here, but also to all the others who helped out by either testing or doing contributions to parts of this PR.

For future readers:
Please report bugs you find in this via the issue form. 
We'll try to fix as many identified problems as possible until the next release (~end of April).

**Comment by samgermain** [comment]
>  We'll try to fix as many identified problems as possible until the next release (~end of April).

Does that mean you'll merge it at the end of April?

**Comment by xmatthias** [comment]
> Does that mean you'll merge it at the end of April?

To stable ... yes (that's then the release).
to develop - once ci completes.

**Comment by donjonson** [comment]
This is an amazing start.  Do you plan to add Any US friendly exchanges or the supportedist of exchanges with futures trading?

**Comment by samgermain** [comment]
> This is an amazing start. Do you plan to add Any US friendly exchanges or the supportedist of exchanges with futures trading?

Which exchanges are you thinking of? 

Regarding the supported list... probably eventually, ftx is only cross margin, which isn't developed yet, but there's a cross branch

I might add Huobi sometime soon, bittrex has no leverage, I don't think kraken's api gives the information we need and the futures exchange class isn't merged into CCXT yet

**Comment by Adilzade** [comment]
Amazing work! Thank you a lot. It works great on Binance exchange but i think there is a problem with shorting. I took Supertrend strategy from freqtrade repository and it simply do not short. I have test it approximately for a week and bot do not enter short. Only long trades. I control it via Telegram bot.Are you aware of this ? Btw freqtrade did not give any erorr while running.I can provide any additional info if you wish.

**Comment by xmatthias** [comment]
> I have test it approximately for a week and bot do not enter short

Feel free to open an issue (with issue template and logs ... ) if you're sure you've configured everything correctly, and are using a strategy that can actually short (you have a backtest of the strategy that shows that it'll do shorts).

The most likely cause is however a misconfiguration (or usage of a strategy that's not made for shorts).

**Comment by Adilzade** [comment]
> > I have test it approximately for a week and bot do not enter short
> 
> Feel free to open an issue (with issue template and logs ... ) if you're sure you've configured everything correctly, and are using a strategy that can actually short (you have a backtest of the strategy that shows that it'll do shorts).
> 
> The most likely cause is however a misconfiguration (or usage of a strategy that's not made for shorts).

Okay, will do that ASAP.

**Comment by urosmarinkovic** [comment]
hey, really amazing project! i was wondering, is there any example of short trading strategy available or maybe if somebody would be kind enough to share an example, would be eternally grateful!

**Comment by xmatthias** [comment]
There is a demo short strategy provided as sample.

it may be profitable, it may not be - depends on markets, timeframes, ... as well as expectations.

**Comment by urosmarinkovic** [comment]
great! it doesn't have to be profitable, i'm still learning and would only like to se how it's used.  where would i find it?

**Comment by xmatthias** [comment]
Assuming you followed the install instructions - in your user_data/strategies directory.

The github link would be this:
https://github.com/freqtrade/freqtrade/blob/develop/freqtrade/templates/sample_strategy.py


You may also wanna check out the [freqtrade strategy repo](https://github.com/freqtrade/freqtrade-strategies/) - which also contains some (converted!) short strategies.
as with all strategies you find on the internet - do your due diligence, try to understand how they work, and what to expect by backtesting in your markets before going to dry-run or live with any strategy.

**Comment by urosmarinkovic** [comment]
thank you for explaining it so kindly, much appreciated! i'm trying to develop my own however, but the idea of short implementation is so exciting! thank you!

**Comment by urosmarinkovic** [comment]
since stoploss is not an optional parameter, how is that handled? i tried with =-1 but it just sells in loss. does direction have to be specified? sorry to bother, just trying to make sense of how it should be used.

**Comment by xmatthias** [comment]
stoploss is relative to profit - not relative to price. the [documentation](https://www.freqtrade.io/) will help you for such things.

**Comment by urosmarinkovic** [comment]
sorry to bother, is there a way to get entry and current price somehow? I can't find anything on the subject.

**Pull request merged**
