### PR TITLE
minor: Add example of usage for Aroon, Aroon Oscillator

### PR DESCRIPTION
**Pull request by hroff-1902**
...into comment in the SampleStrategy.
(from Slack)

### CODE REVIEW

**Comment by hroff-1902** [comment]
travis-ci/pr is finished in the Details, but is pending here...
refreshing in the browser does not help...

**Comment by xmatthias** [comment]
> travis-ci/pr is finished in the Details, but is pending here...

not the first time - probably won't be the last time ... one more reason why i don't like travis anymore - and "movement away" did start already ;)

**Comment by hroff-1902** [comment]
Yeah, right, 
and I did not merge this PR by myself for you to have a chance to have a look at this...
(since this probably is related to the recent changes you made to the github automation or how it's called...)

**Comment by xmatthias** [comment]
no, it's travis not updating github ... - happened a few times well before i added the first commit related to github actions.

you could force it by rerunning the travis check (i think you need to log in there to be able to do that).

**Pull request merged**
