### PR TITLE
Add support for trailing_stop_loss order_type

### PR DESCRIPTION
**Pull request by rextea**
## Summary
Add an optional parameter to set a custom order_type for trailing_stop_loss sell reason

## What's new?
Add an optional parameter to set a custom order_type for trailing_stop_loss sell reason

### CODE REVIEW

**Review by xmatthias — CHANGES_REQUESTED** [review]
Except for the fact that i don't understand why we'd need this, it's also not working the way you expect it to (at least not with stoploss on exchange).

A regular stoploss and trailing stoploss are not different - 
the "trailing" version replaces the initial stoploss, there's no benefit i can see to using different types for this.
If the reason for this is the risk of blowing past the trailing "limit" stoploss order (or not getting that filled) - then having "stoploss" set to "market" will not help you, as the initial stoploss will NOT be in place any longer - and will fore be ignored.

That's why i recommend using stoploss on exchange - as it'll make sure your stop is placed "early". While there's still a minimal risk of blowing past that stoplos on very violent moves - i'm yet to see ONE case where that happened.

**Comment by rextea** [comment]
I've fixed the behavior of it, now it should work the way I've expected. (although the execute_sell method is too complicated according to flake8)
As for why it's needed, you may be right with setting stoploss on exchange, i'll give it a try. but still maybe for cases where you don't use stoploss on exchange it may be usuful.

**Comment by xmatthias** [comment]
i'm not sure i see why ... even without "stoploss on exchange" there's no real difference between the 2 sells - other than the fact that the trailing one has been raised multiple times, and is therefore closer to current price.

**Comment by rextea** [comment]
In a case where I want the stoploss to sell on market (to avoid timeout of stoploss - happend to me couple of times), but as for trailing stop loss I care less if it will timeout and I prefer to take as much profit I can - that's why I want it to be limit sell

**Comment by xmatthias** [comment]
I don't think this will give you what you want.
Assuming the trailing stop will timeout - then the bot will try to replace it with a new limit order, which can eventually again timeout.

Assuming your first "trailing stop" hit was at 2% profit - you can go down to -5% (or down to -20%) following the price with this method, each trailing-stop order timing out (it will NOT fall back to the original stoploss once it started trailing).

**Pull request closed without merging**
