### PR TITLE
Added command line options to override max_open_trades and stake_amount

### PR DESCRIPTION
**Pull request by konqueror1**
## Summary
With this PR we can override config options "max_open_trades" and "stake_amount" with the command line.

### CODE REVIEW

**Comment by mishaker** [comment]
sorry why do you want to do that? we can also add all other configs to command line but then what for ?

**Comment by konqueror1** [comment]
@mishaker 
These two options are useful for my backtests. It is easier to find the best ratio without editing the config before every test.

**Comment by hroff-1902** [comment]
With explaination above, this may have some sense... LGTM

* flake to be happy
* tests for new options

Please do not assign short options (one letter) for them. Just imho.

**Comment by xmatthias** [comment]
Fixed the flake8 probs, apart from that looks good to me.

**Pull request merged**
