### PR TITLE
prevent hyperopt from running multiple instances simultaneously

### PR DESCRIPTION
**Pull request by hroff-1902**
Set and check the lock.

Inspired by #1803.

A universal approach (py-filelock) was choosen because a custom one with fcntl/flock is 1) platform specific, 2) a lock set on the results pickle file can persist in case the app was killed in the middle. Can be problematic for an inexperienced user to remove the lock.

* I tested it with graceful hyperopt exit, `Ctrl+C`, `kill` and `kill -9` (Ubuntu).
* @xmatthias, you can adjust the log messages if you wish.
* Please test it on Windows.
* A test for it should probably be added. Too complicated for me, I'm still not quite familiar with all that mocking stuff...
* Docs should mention it somehow if recently added sentence about multiple Heperopts does not suffice.
* TODO (sep. PR, future): start() for Backtesting, Edge and Hyperopt should return boolean in order to return non-zero exit code in some cases. (or simply raise an exception to freqtrade here if the lock is detected?)

### CODE REVIEW

**Comment by xmatthias** [comment]
> A test for it should probably be added. Too complicated for me, I'm still not quite familiar with all that mocking stuff...

for me too ... 
the only idea to test this even remotely is to use multiprocessing for the tests - have one thread wait a bit and see if the other thread still holds the lock.

I am however not sure if the effort justifies the outcome - hyperopt is not well covered by tests anyway ... 


One thing that surprised me though is that the lockfile remains there even after the execution.
It's "somehow" working to detect that it's not locked anymore (i assume that's a feature of that library?) ... but it's still surprising (and kills my only other idea for a test).

**Comment by hroff-1902** [comment]
> One thing that surprised me though is that the lockfile remains there even after the execution.
> It's "somehow" working to detect that it's not locked anymore (i assume that's a feature of that library?) ... but it's still surprising (and kills my only other idea for a test).

Me too (surprised, I also noticed it). Well, I specially tested it with kill -9 and other approaches to terminate the process (as mentioned above) -- I did not found conditions where a hanging lock is left when the locking process is not alive... Seem's to be okay, a solid working solution, as to me...

A bit lazy in the moment to stady the sources of lockfile, may be later...

**Comment by xmatthias** [comment]
Nah that's fine, no reason to do that - just surprised, is all.
I'll have a look at this monday (won't be at my windows test-pc before then) - if it works there too it's good to me :+1:

**Comment by hroff-1902** [comment]
Included into #1775 as a part of enhancements to hyperopt

**Pull request merged**
