### PR TITLE
Order creation

### PR DESCRIPTION
**Pull request by iuvbio**
## Summary
Significantly reduces code repetition by moving exception handling and dry order handling to separate methods.

Solve the issue: #1574

## Quick changelog

- added `dry_run_order`
- added `create_order`

## What's new?
Adds a method to create dry orders that works for all order types. Also adds a `create_order`, a wrapper around ccxt's `create_order`, method to exchange which takes care of exception handling. There is one drawback, the exception messages for `stoploss_limit` are now identical to the ones for other orders, however, since the log outputs the details that are now omitted in the exception messages on each order creation, I think that's fine. Let me know what you think though.

### CODE REVIEW

**Comment by iuvbio** [comment]
Why do we take the stop_price as price in dry_run `stoploss_limit` not limit_price at which trade should happen? The stoploss_price is the trigger and the limit_price the actual rate, right?

```python
if self._conf['dry_run']:
    order_id = f'dry_run_buy_{randint(0, 10**6)}'
    self._dry_run_open_orders[order_id] = {
        'info': {},
        'id': order_id,
        'pair': pair,
        'price': stop_price,
        'amount': amount,
        'type': 'stop_loss_limit',
        'side': 'sell',
        'remaining': amount,
        'datetime': arrow.utcnow().isoformat(),
        'status': 'open',
        'fee': None
    }
```

**Comment by iuvbio** [comment]
Just spent a while trying to find out why `test_freqtradebot.py` fails on so many tests when buy and sell dry run also return the complete dry_order dict. Still couldn't figure it out. Any idea @xmatthias ?

**Comment by xmatthias** [comment]
Can you push the code and I'll have a look over the weekend.

not every commit needs to pass CI ... just the last one ;-)

**Comment by iuvbio** [comment]
Done. All tests fail on `execute_buy`, specifically

```
        # in case of FOK the order may be filled immediately and fully
        elif order_status == 'closed':
>           stake_amount = order['cost']
E           KeyError: 'cost'

freqtrade/freqtradebot.py:427: KeyError
```
 `test_exchange.py` passes fine.

It's clear that the or returned does apparently not contain all the necessary data. The strange thing is that it works when only `{"id": order_id}` is returned (as originally for buy/sell). So my guess is that some mock updates the dry order and this does not happen if the dict is different. But yea, I don't have much experience with magic mock, so you can probably figure it out faster.

**Comment by xmatthias** [comment]
the solution is simple and odd at the same time ...

The mistery is in the following line:

https://github.com/iuvbio/freqtrade/blob/9a097214a615f40aa10473b13984cf5d61a7c9d2/freqtrade/freqtradebot.py#L396
``` python
        order_status = order.get('status', None)
```

if `status` is absent, then the whole subsequent if/elif block does not apply / is skipped.

It's stupid that it fails / comes up in this PR - but it's an oversight from a test point of view, which was never apparent since only 'id' was added.

I think the best would be to add "cost" to the dry-run return-values - since it's a valid return-value - and should be easy to calculate. The result is similar to stake_currency - but can be slightly off due to "rounding" 
for a calculation example look here:

https://github.com/ccxt/ccxt/blob/48e79491a2f6d65decd57d862e20e39ba316a17f/python/ccxt/binance.py#L602

**Comment by iuvbio** [comment]
Of course.. :man_facepalming: thanks!

There were two more tests in rpc that failed, because basically the tests assumed the trades created by `create_trade` to be open order, which makes sense. This was achieved by just returning the order id and status None as you said. However, the dry orders were stored as closed, which also make sense. I added a helper function that "closes" dry orders and stores them, but the buy and sell methods still return them as open. I think like this it's quite clean, let me know what you think.

**Pull request merged**
