### PR TITLE
Allow logging to file

### PR DESCRIPTION
**Pull request by xmatthias**
## Summary
Add logging to file as an option.
Also change standard-logging to stdout instead of stderr, to allow easier handling when piping the output to something else.

Solve the issue: multiple questions on Slack

## Quick changelog

- log to stdout
- additionally log to rotating file (10 files, 1M each).

### CODE REVIEW

**Comment by hroff-1902** [comment]
What about logging.config? https://docs.python.org/3/library/logging.config.html
It's much more flexible...

**Comment by xmatthias** [comment]
it's more flexible - but takes away the possibility to quickly configure something quickly with one command and without being a developer - at least as far as I've seen when quickly looking at it.

I personally think this will suffice for our needs and will be a lot better than what we currently have - but it's just my opinion, not set in stone, and I'm not upset if another solution is considered better. 

Note: When I open a PR, I'm just a contributor like everyone else, my role with this project does not matter in these cases.

**Comment by hroff-1902** [comment]
> it's more flexible - but takes away the possibility to quickly configure something quickly with one command and without being a developer - at least as far as I've seen when quickly looking at it, since I was not aware of this until now.

Agree. So in the future there can be two options, --log-file and, say, --log-config (only one of them can be used in the same time, I assume in the meantime), --log-file allows quick redirection to choosen logfile while --log-config suggests more sufficticated controll on aspects of the logging, if one need it for some reasons...

**Comment by xmatthias** [comment]
absolutely - but I assume that 95% (or more) of the times a quick log-to-file is enough ... as most other possibilities require external setups (syslog-server, ...).

**Comment by mishaker** [comment]
@hroff-1902 I am going to merge this PR as I also think a simple log file as implemented here does the job. but feel free to do another PR if you think it is necessary :)

**Comment by hroff-1902** [comment]
> @hroff-1902 I am going to merge this PR as I also think a simple log file as implemented here does the job. but feel free to do another PR if you think it is necessary :)

Exactly...

**Pull request merged**
