### PR TITLE
Coingekko replacing coinmarketcap

### LINKED ISSUE #3028: Fiat convert not working
## Step 1: Have you search for this issue before posting it?

If you have discovered a bug in the bot, please [search our issue tracker](https://github.com/freqtrade/freqtrade/issues?q=is%3Aissue). 
If it hasn't been reported, please create a new issue.

## Step 2: Describe your environment

  * Operating system: ubuntu 18.04
  * Python Version: 3.6.9 (`python -V`)
  * CCXT version:  (`pip freeze | grep ccxt`)
  * Branch:  Develop
  * Last Commit ID: no git (`git log --format="%H" -n 1`)

asn1crypto==0.24.0
cryptography==2.1.4
enum34==1.1.6
idna==2.6
ipaddress==1.0.17
keyring==10.6.0
keyrings.alt==3.0
pycrypto==2.6.1
pygobject==3.26.1
pyxdg==0.25
SecretStorage==2.3.1
six==1.11.0
  
## Step 3: Describe the problem:

*Explain the problem you have encountered*

### Steps to reproduce:

  1. On my telegram bot I click `/daily` or any other function that included GBP
  
image

All my currency values have changed to 0 or they have disapeared. This has happened for all functions that show currency values.  When i click `status table` the currency has disapeared entirely. 
  
### Observed Results:

  * What happened?
While on telegram all currency values have changed to 0 or disapeared. I have queried the trades in my database and things seem to be normal. However, I am not sure whether the database stores actual currency values or whether the crypto values are converted to GBP by the bot or extracted from binance. 
  * What did you expect to happen?
For the actual values to show.
### Relevant code exceptions or logs:

using docker so cant get logs

  ```
  // paste your log here
  ```

### PR DESCRIPTION
**Pull request by xmatthias**
## Summary
With the removal of the free option from coinmarketcap (the option without API key), and the non-support from the coinmarketcap-library we've been using so far, we need an alternative option to convert crypto to fiat.

This solution is based mostly on https://github.com/freqtrade/freqtrade/issues/3028#issuecomment-595810578 - however includes tests and so forth.

Closes #3028

## Quick changelog

- Remove coinmarketcap
- Add coingekko for FIAT conversation

Further work may look at removing the hardcoded list of supported fiat currencies ... coingekko seems to support more than what we got in the list.

However, that'll be done in a seperate PR as that will require custom validation of the value provided in the configuration.

### CODE REVIEW

**Comment by Fredrik81** [comment]
Missing some docs updates

**Comment by xmatthias** [comment]
> Missing some docs updates

where? we don't mention coinmarketcap now ...

**Comment by Fredrik81** [comment]
> > Missing some docs updates
> 
> where? we don't mention coinmarketcap at the moment - at least not as far as i could find ... ?

./docs/utils.md

Also is same Fiat coins supported?

**Comment by xmatthias** [comment]
it's technically more - but i'd like to use a dynamic list as mentioned above ... as i suspect that the list can change ... so using a list as we have it now in constants.py will not be sustainable.

however - i'd like to keep that in a seperate PR  ... as i'll still need to find the correct place to validate the setting against the coin.

**Pull request merged**
