### PR TITLE
fix: code quality issues

### PR DESCRIPTION
**Pull request by withshubh**
### Description
Hi :wave: I work at [DeepSource](https://deepsource.io), I ran DeepSource analysis on the forked copy of this repo and found some interesting [code quality issues](https://deepsource.io/gh/withshubh/freqtrade/issues/?category=recommended) in the codebase, opening this PR so you can assess if our platform is right and helpful for you.

### Summary of changes

- Removed unnecessary comprehension
- Removed unnecessary use of comprehension
- Removed length check in favour of truthiness of the object
- Removed methods with unnecessary super delegation
- Refactored unnecessary `else` / `elif` when `if` block has a `continue` statement
- Merged `isinstance` calls
- Refactored the comparison involving `not`
- ~Added .deepsource.toml to continuously analyze the repo~

### CODE REVIEW

**Comment by xmatthias** [comment]
hi @withshubh,

I hope you are not just dumping out semi-automated Pull-requests to random projects in order to promote your tool - but are also following up on the Pull requests with the intend to make them mergable.

While the changes themselfs look good - CI is failing due to flake8 errors - so we will not be able to merge these unless the errors are fixed.


For your project / company - you should consider moving the configuration file into a directory that exists in most repositories (`.github`) to keep the project root clean. 
There's too many projects already dumping random files in the project root - which is the main landing page of each project's github presence.

Therefore, (if deepsource supports it) - please move the  `.deepsource.toml` file to the .github directory, or remove it (in this case, we will not use deepsource for now for sure, as it would mean yet another config file with unclear benefits).

**Comment by withshubh** [comment]
> hi @withshubh,
> 
> I hope you are not just dumping out semi-automated Pull-requests to random projects in order to promote your tool - but are also following up on the Pull requests with the intend to make them mergable.
> 
> While the changes themselfs look good - CI is failing due to flake8 errors - so we will not be able to merge these unless the errors are fixed.

Hey @xmatthias — all changes proposed were not automated but done manually. I’ve fixed the flake8 errors to make CI happy :)

> For your project / company - you should consider moving the configuration file into a directory that exists in most repositories (`.github`) to keep the project root clean.
> There's too many projects already dumping random files in the project root - which is the main landing page of each project's github presence.

Regarding the location of the `.deepsource.toml` file, we won't’ be able to move it to .github directory as it holds GitHub specific configuration. At the moment, the configuration has to be at the root of the repository. I’ve removed the `.deepsource.toml` file in this PR. I will pass on your feedback to the team.

> Therefore, (if deepsource supports it) - please move the `.deepsource.toml` file to the .github directory, or remove it (in this case, we will not use deepsource for now for sure, as it would mean yet another config file with unclear benefits).

Benefit of using DeepSource: As of today, DeepSource Python analyzer can detect over 561 types of issues and will be able to catch them all on future pull requests, continuously. Here’s the analysis result for the repo - https://deepsource.io/gh/withshubh/freqtrade/issues/
Hope that helps. Thanks!

**Review by xmatthias — APPROVED** [review]
That's great then, thanks!

I'm just ... cautious as we've had automated PR's in the past - and bot's "usually" don't follow up 😆 

I'll have a look at Deepsource - any hints / resources at what be different between deepsource an deepcode (which i tried sometime in the past)?
both seem to do similar things ... so maybe you have a "comparison" at hand you can share?

for this PR however: LGTM 👍

**Comment by withshubh** [comment]
> I'm just ... cautious as we've had automated PR's in the past - and bot's "usually" don't follow up :laughing:

totally understandable 😂
> I'll have a look at Deepsource - any hints / resources at what be different between deepsource and deepcode (which I tried sometime in the past)?
both seem to do similar things ... so maybe you have a "comparison" at hand you can share?

Some of the added benefits that DeepSource offers:

- Automatic code formatting to comply with the code style (through Transformers).
- Option to Autofix detected issues through one click.
- DeepSource Python analyzer detects 520 issues as of now (new support being continuously added).
- Less than 5% false positive reports in DeepSource.
- Option to report false positives directly.
- Much better integration and developer experience.

**Pull request merged**
