### PR TITLE
Corrected test_create_order

### PR DESCRIPTION
**Pull request by SmartManoj**
Thank you for sending your pull request. But first, have you included
unit tests, and is your code PEP8 conformant? [More details](https://github.com/freqtrade/freqtrade/blob/develop/CONTRIBUTING.md)

## Summary

Solve the issue: #___

## Quick changelog

- <change log 1>
- <change log 1>

## What's new?

*Explain in details what this PR solve or improve. You can include visuals.*

### CODE REVIEW

**Review by xmatthias — APPROVED** [review]
LGTM 👍

**Comment by SmartManoj** [comment]
Previously, rate was passed for a market order with `createMarketBuyOrderRequiresPrice:None` and it is ignored.
It would be better to rename rate to api_rate or rate_for_order? and revert the changes to check whether it is ignored or not?

**Comment by xmatthias** [comment]
rate is not technically ignored - it's still used to determine the amount, also on market orders.

Testing the "non-use" was for sure never the intend in this test - so i think this change is fine.

**Comment by SmartManoj** [comment]
> rate is not technically ignored - it's still used to determine the amount, also on market orders.

amount is passed to `create_order`

**Comment by xmatthias** [comment]
it still isn't asserted if rate is passed to the api call or not - so that's clearly not the intend of the test.

**Comment by SmartManoj** [comment]
It is asserted.
https://github.com/freqtrade/freqtrade/blob/ddb0254999f920dbcd07abe366185cc4b4b9bd3e/tests/exchange/test_exchange.py#L1110

**Pull request merged**
