### PR TITLE
Manual bump to ccxt 1.18.1159

### PR DESCRIPTION
**Pull request by hroff-1902**
(support for binance.us)

### CODE REVIEW

**Comment by xmatthias** [comment]
it's just a nice to have / allow our users to use binance.us (couldn't find that quickly looking through ccxt)? 

or is something broken without this (in which case i would also increment the min version in `setup.py`).

**Comment by hroff-1902** [comment]
> it's just a nice to have / allow our users to use binance.us (couldn't find that quickly looking through ccxt)?
> 
> or is something broken without this (in which case i would also increment the min version in `setup.py`).

nothing broken, just to allow usage of new exchange, asked at Slack

**Comment by hroff-1902** [comment]
ah, `setup.py`, I always forgetting about this...
But was not aligned with the version stated here, in `requirements-common.txt`...
When should we change `setup.py`?

**Comment by hroff-1902** [comment]
Thanks. Right, we have a separate class for binance...

**Pull request merged**
