### PR TITLE
Re-add ticker caching for rpc operations

### PR DESCRIPTION
**Pull request by xmatthias**
## Summary
this readds ticker caching for rpc operations as `/status table` becomes very slow (takes a few seconds to respond - but does not need up to the second accurate data).

Solve the issue: #856

## Quick changelog

- Reinstate ticker caching (was half-intentionally dropped during ccxt move as we didn't think to require it).
- Add tests to verify it's correct implementation.

### CODE REVIEW

**Comment by jblestang** [comment]
Should we cache bid, ask or last? Maybe last would be better no?

**Comment by xmatthias** [comment]
well - i checked how it was done in your old PR - and that used all 3 (but i checked - rpc uses `['bit']` only...)

will have a look at coveralls

**Comment by gcarq** [comment]
@xmatthias I think we should cache the whole response, otherwise it could be an issue if we rely on additional fields in the future.

Maybe we should also rephrase the `refresh` argument into `cache` and only read/write to the dict if cache is `True`. That would lower the memory usage a bit in cases where the cache is never used.

**Comment by xmatthias** [comment]
I disagree (or only partially understand maybe) this.

If we only cache if `refresh` (or `cache` - as it's called then) is true - then we would refresh once `/status table` is called - but never thereafter unless we implement our own "cache for X minutes / hours" logic. 
The way it is implemented in this PR currently it would always have the data from the last cycle cached - so `/status table` should not be more out of date than a few minutes.
It's actually a replication of the logic in #293.

My intend with caching only needed pieces was to keep memory usage low as the response from ccxt is "fairly" big - with not much in it we really use.

personally, i would extend the cached values "as needed" - as that will keep memory usage as low as possible.

``` 
{'symbol': 'XRP/ETH',
 'timestamp': 1528308743343,
 'datetime': '2018-06-06T18:12:23.343Z',
 'high': 0.00112098,
 'low': 0.001102,
 'bid': 0.00110201,
 'bidVolume': 22.0,
 'ask': 0.00110369,
 'askVolume': 1023.0,
 'vwap': 0.00110923,
 'open': 0.00111499,
 'close': 0.00110201,
 'last': 0.00110201,
 'previousClose': 0.00111399,
 'change': -1.298e-05,
 'percentage': -1.164,
 'average': None,
 'baseVolume': 3023794.0,
 'quoteVolume': 3354.07065316,
 'info': {'symbol': 'XRPETH',
  'priceChange': '-0.00001298',
  'priceChangePercent': '-1.164',
  'weightedAvgPrice': '0.00110923',
  'prevClosePrice': '0.00111399',
  'lastPrice': '0.00110201',
  'lastQty': '51.00000000',
  'bidPrice': '0.00110201',
  'bidQty': '22.00000000',
  'askPrice': '0.00110369',
  'askQty': '1023.00000000',
  'openPrice': '0.00111499',
  'highPrice': '0.00112098',
  'lowPrice': '0.00110200',
  'volume': '3023794.00000000',
  'quoteVolume': '3354.07065316',
  'openTime': 1528222343343,
  'closeTime': 1528308743343,
  'firstId': 8606049,
  'lastId': 8616511,
  'count': 10463}}

```

**Comment by gcarq** [comment]
@xmatthias I didn't know the response was that big, now I see your point. I'm fine with that for now.

**Pull request merged**
