### PR TITLE
Improve PCA and pairwise distance calcs

### PR DESCRIPTION
**Pull request by lolongcovas**
## Summary

Ignore the sample itself distance in the `avg_mean_dist` computation.
Fix the PCA computation when the test is empty.

### CODE REVIEW

**Comment by robcaulk** [comment]
Hey, the code itself is correct, but it is not [passing](https://github.com/freqtrade/freqtrade/runs/7879329301?check_suite_focus=true#step:9:12) flake8. Make sure you have pre-commit installed:

https://www.freqtrade.io/en/stable/developer/#developer-setup

And ensure you have flake8 plugin installed in your IDE to help you detect the issues.

**Comment by robcaulk** [comment]
Hey I think there was an issue in the pipeline, can you make another small commit (maybe comment one of the lines) so that the CI tries to merge this correctly?

**Comment by lolongcovas** [comment]
> Hey I think there was an issue in the pipeline, can you make another small commit (maybe comment one of the lines) so that the CI tries to merge this correctly?

does it have a `rerun` button?

**Comment by robcaulk** [comment]
https://discord.com/channels/700048804539400213/702584313354518659/1009721577178402878

**Comment by robcaulk** [comment]
Please don't remove lines from random files that have nothing to do with the PR  (FreqaiExampleStrategy.py) :-) This pollutes the contribution log in my opinion. 

Please undo that change. The pipeline looks like it should pass after you do that.

**Comment by robcaulk** [comment]
LGTM!

**Review by robcaulk — APPROVED** [review]

**Pull request merged**
