### PR TITLE
Add SKDecimal Space

### PR DESCRIPTION
**Pull request by xmatthias**
## Summary
Add a real Decimal Scikit-optimize space

This will **break** how the current decimal space works / loads it's parameters, as it's fully using the final results for the calculations - but that's not yet in any release, so ... 

This is still a "wip" - and i don't really expect tests to pass ...

## Quick changelog

- introduce Decimal space for hyperopt
- 

@rokups - would you mind having a look at this too? as the original implementation for the decimal space came from you

### CODE REVIEW

**Comment by rokups** [comment]
Looks great! Though you forgot to clean up few `attr._set_value(params[attr_name])` instances.

**Comment by xmatthias** [comment]
> Though you forgot to clean up few `attr._set_value(params[attr_name])` instances.

I'm not sure i want to remove these ...
setting the value is still necessary, so it'd be a replacement of `attr._set_value(params[attr_name])` with `attr.value = params[attr_name]` - which i'm not sure gives us much benefits for now ...

**Comment by rokups** [comment]
I only added that to handle conversions. At this point keeping it seems rather pointless 👀 also `attr.value = params[attr_name]` is much cleaner as that would be all this function does anyway

**Comment by xmatthias** [comment]
Good point :+1:

**Pull request merged**
