### PR TITLE
gateio market orders futures

### PR DESCRIPTION
**Pull request by samgermain**
Gateio futures allows market orders, just not spot

### CODE REVIEW

**Review by xmatthias — APPROVED** [review]
i guess this is a point we'll need to look at separately, anyway (not just for gate.io)

i suspect we'll find several instances of some limitations being different (like spread-filter not working for binance futures).

**Comment by samgermain** [comment]
> i guess this is a point we'll need to look at separately, anyway (not just for gate.io)
> 
> i suspect we'll find several instances of some limitations being different (like spread-filter not working for binance futures).

Binance, Gateio, Kraken, and Kucoin have separate api endpoints for their futures exchanges
Okex and FTX use the same endpoints.

In particular though, gateio decided to make their spot and futures api's basically nothing alike, bybit was also horrible in that regard, kraken wasn't great

**Comment by xmatthias** [comment]
No what i mean is - which features are identical - which aren't.
even if the endpoint is identical - that doesn't mean that the same order-types / time-in-force, ... apply to both.

**Comment by samgermain** [comment]
> No what i mean is - which features are identical - which aren't. even if the endpoint is identical - that doesn't mean that the same order-types / time-in-force, ... apply to both.

It usually does

**Comment by samgermain** [comment]
@xmatthias This error still happens                     `'Exchange Gate.io does not support market orders.')`

**Comment by xmatthias** [comment]
for non-futures markets, that seems to be the correct approach?

It's technically ccxt's fault. the setting for `createMarketOrder` is set to false - even if i start the exchange in futures mode. 

https://github.com/ccxt/ccxt/blob/ac9f9fe5bf6a78dfb37ef354d268d4da20cd8ee2/js/gateio.js#L42

so ccxt is telling freqtrade "i cannot trade market orders on this exchange". 
While we do have an explicit check for gate.io - the main driver is ccxt (ccxt will have to handle our order after all).

I assume this "has" would have to change based on the init type (if we start with default_mode swap - the "has" entries would need to look different for gate.io - which apparently isn't happening).

**Pull request merged**
