### PR TITLE
Enable ratelimit

### LINKED ISSUE #1764: enableRateLimit should be switched to true by default in the config and defaults
In the default config use
```
"ccxt_async_config": {
            "enableRateLimit": true
        },
```
... And probably in the default value.

Reason:
With current config and defaults Bittrex blocks new inexperienced users who just started evaluation of the bot and use default config for that.

### PR DESCRIPTION
**Pull request by xmatthias**
## Summary
Enable rate-limit by default so new users don't encounter bans and document this behaviour.

Resolves #1764

## Quick changelog

- Enable rate-limit by default 
- Add documentation for this parameter
- remove deprecated parameter for setting rate-limit.

### CODE REVIEW

**Comment by hroff-1902** [comment]
TODO: move description of the deprecated option from configuration.md to deprecated.md

**Comment by xmatthias** [comment]
it was deprecated but is now gone ... ?

**Comment by hroff-1902** [comment]
> it was deprecated but is now gone ... ?

Hmm, seems I missed something...

**Comment by xmatthias** [comment]
we used to have the option `exchange.ccxt_rate_limit` ... which set the rate-limit for the async exchange.
that was limiting, as ccxt has many more (sometimes exchange specific) options we wanted to expose.
we left this in for compatibility - but with this i removed that part.

**Pull request merged**
