### PR TITLE
Add range property to CategoricalParameter.

### PR DESCRIPTION
**Pull request by rokups**
At the moment we can keep a single code path when using IntParameter, but we have to make a special hyperopt case for CategoricalParameter. Range property solves this.

### CODE REVIEW

**Comment by xmatthias** [comment]
in general - absolutely (we should also add `.range` to the DecimalParameter ...)
what's missing here is the docs - and maybe a very quick test (i'm always afraid to break functionality unintentionally later on 😆 )

**Comment by rokups** [comment]
Ill take care of DecimalParameter and tests 👍🏻

**Comment by rokups** [comment]
CI failure a random fluke?

**Review by xmatthias — APPROVED** [review]
Great! thanks a lot :100: 

LGTM :+1:

**Pull request merged**
