### PR TITLE
Fix dry run stop price in case of stoploss on exchange

### PR DESCRIPTION
**Pull request by mishaker**
## Summary
If a stoploss is hit in Dry-run mode the sell price has to be the stop price not anything else.
100$ with 0.01 stoploss means the sell price is 99$ if the stoploss is hit on dry-run. 

In live it could be differ though. As it is defined by the spot price as well as the exchange liquidity.

### CODE REVIEW

**Comment by xmatthias** [comment]
i'm honestly not sure about this (not technically - but from a logic perspective).
the price is probably lower than stoploss if the price moves fast against you (assume a 4$ drop).

it may be similar/exactly to the  configured stoploss when using stoploss on exchange - but in "regular mode", i think that the "current" rate we use currently is more precise / reflecting reality better (especially when using market as stoploss sells). 
I think this approach would align dry-run to backtest better - however move it further away from "live" mode

i know backtesting uses stoploss as the sell-price in stoploss-scenarios now - however that's because we don't have better data during backtesting...

**Comment by mishaker** [comment]
Maybe I should add if stoploss on exchange ...

**Comment by xmatthias** [comment]
if it's only intendet for use with "stoploss on exchange" - then yes. 
Rest looks fine - but this makes #1341 blocker / candidate for merge first (otherwise the option you're checking for won't exist, and it'll break ).

**Comment by mishaker** [comment]
@creslinux I would like to ask your opinion on this one. 
For me dry-run should not consider liquidity on the exchange. so stoploss hit means sell occurred at stop price. but I can understand @xmatthias concerns. a workaround can be including it just for stoploss on exchange. let us know what you think.

**Pull request merged**
