### PR TITLE
Fix no tickerdata for pair for open trades

### PR DESCRIPTION
**Pull request by xmatthias**
## Summary

Solve the issue: #1298

## Quick changelog

- include pairs from open trades to active-whitelist to make sure ticker-data is downloaded
- don't overwrite pair-whitelist in config dict to avoid facing an empty list if markets where down for a short amount of time when not using dynamic whitelist.

### CODE REVIEW

**Comment by xmatthias** [comment]
not overwriting `self.config['exchange']['pair_whitelist']` fixes a slightly different bug - which could appear on static whitelists after the exchange is temporarily unavailable. 
We'd overwrite this list with an empty list (no market open -> returns empty) - which results in a state where the bot is unable to trade as it has no whitelisted pairs - and it doesn't find that markets are open again since we've overwritten the allowed pair list - and can't recover since dynamic whitelist is not enabled.

`_process` is the "first thing" that happens - I could also use an empty array in `__init__` - as the only variable used while running is `self.active_pair_whitelist` - which is generated by using all active markets from `"pair_whitelist"` - + all open trade pairs (should there be any not in the whitelist anymore).

**Comment by doftorul** [comment]
I have applied the commit, the issue still persists.
2018-10-29 15:37:26,372 - freqtrade.freqtradebot - DEBUG - Handling Trade(id=104, pair=LINK/BTC, amount=43.00000000, open_rate=0.00006894, open_since=2 days ago) ...
2018-10-29 15:37:26,861 - freqtrade.strategy.interface - WARNING - Empty ticker history for pair LINK/BTC

 2018-10-29 15:37:27,859 - freqtrade.freqtradebot - DEBUG - Handling Trade(id=124, pair=SKY/BTC, amount=6.06000000, open_rate=0.00049500, open_since=a day ago) ...
2018-10-29 15:37:28,368 - root - DEBUG - TA Analysis Launched
2018-10-29 15:37:28,384 - root - DEBUG - Loop Analysis Launched
2018-10-29 15:37:28,385 - freqtrade.strategy.interface - WARNING - Outdated history for pair SKY/BTC. Last tick is 257 minutes old

**Comment by doftorul** [comment]
Tested for about 1 hour, all the pairs with issues seem to be correctly updated although they are not in the dynamic-whitelist 75 in my case.
No more WARNING messages related to the tick history in the DEBUG.

Thank you @xmatthias

**Comment by mishaker** [comment]
@doftorul thank you for testing and reporting back :)

**Pull request merged**
